// @flow
export const CHANNEL_ARCHIVED_FAILED_NO_PERMISSIONS =
  'CHANNEL_ARCHIVED_FAILED_NO_PERMISSIONS';
export const CHANNEL_ARCHIVED_FAILED_ALREADY_ARCHIVED =
  'CHANNEL_ARCHIVED_FAILED_ALREADY_ARCHIVED';
export const CHANNEL_ARCHIVED_FAILED_GENERAL =
  'CHANNEL_ARCHIVED_FAILED_GENERAL';

export const CHANNEL_RESTORED_FAILED_NO_PERMISSIONS =
  'CHANNEL_RESTORED_FAILED_NO_PERMISSIONS';

export const NO_PERMISSION_SEND_MESSAGE = 'NO_PERMISSION_SEND_MESSAGE';
export const MESSAGE_SEND_FAILED_QUOTE_NOT_IN_THREAD =
  'MESSAGE_SEND_FAILED_QUOTE_NOT_IN_THREAD';
