// @flow
export const CHANNEL_ARCHIVED_FAILED_NO_PERMISSIONS =
  'CHANNEL_ARCHIVED_FAILED_NO_PERMISSIONS';
export const CHANNEL_ARCHIVED_FAILED_ALREADY_ARCHIVED =
  'CHANNEL_ARCHIVED_FAILED_ALREADY_ARCHIVED';
export const CHANNEL_ARCHIVED_FAILED_GENERAL =
  'CHANNEL_ARCHIVED_FAILED_GENERAL';

// @flow
export const CHANNEL_CREATED_FAILED_NO_PERMISSIONS =
  'CHANNEL_CREATED_FAILED_NO_PERMISSIONS';
export const CHANNEL_CREATED_FAILED_NAME_RESERVED =
  'CHANNEL_CREATED_FAILED_NAME_RESERVED';
export const CHANNEL_CREATED_FAILED_SLUG_EXISTS =
  'CHANNEL_CREATED_FAILED_SLUG_EXISTS';

export const CHANNEL_RESTORED_FAILED_NO_PERMISSIONS =
  'CHANNEL_RESTORED_FAILED_NO_PERMISSIONS';

export const NO_PERMISSION_SEND_MESSAGE = 'NO_PERMISSION_SEND_MESSAGE';
export const MESSAGE_SEND_FAILED_QUOTE_NOT_IN_THREAD =
  'MESSAGE_SEND_FAILED_QUOTE_NOT_IN_THREAD';
