export const collections = [
  {
    title: 'Top Communities',
    curatedContentType: 'top-communities-by-members',
    communities: [
      'spectrum',
      'codesandbox',
      'codepen',
      'figma',
      'react',
      'specfm',
      'product-design',
      'sketch',
      'styled-components',
      'framer',
      'frontend',
      'wip',
      'abstract',
      'crypto',
      'sketchcasts',
      'tech-tea',
      'design-code',
      'journalism',
    ],
  },
  {
    title: 'Design',
    curatedContentType: 'design-communities',
    communities: [
      'product-design',
      'icon-design',
      'typography',
      'illustrators',
      'design-management',
      'specfm',
      'up-coming',
      'sketchcasts',
      'google-design',
      'design-code',
      'codepen',
      'vectors',
      'designhunt',
      'figma',
      'sketch',
      'framer',
      'abstract',
      'invision',
      'compositor',
      'zeplin',
      'origami-studio',
      'fuse',
    ],
  },
  {
    title: 'Web development',
    curatedContentType: 'development-communities',
    communities: [
      'react',
      'node',
      'codesandbox',
      'vue-js',
      'angular',
      'ember-js',
      'laravel',
      'elixir',
      'styled-components',
      'graphql',
      'css-in-js',
      'electron',
      'android',
      'swiftdev',
      'react-native',
      'frontend',
      'specfm',
      'realm',
      'expo',
      'compositor',
      'codepen',
      'bootstrap',
      'tachyons',
      'divjoy',
    ],
  },
  {
    title: 'Tech',
    curatedContentType: 'tech-communities',
    communities: [
      'tech-tea',
      'balancemymoney',
      'crypto',
      'btc',
      'ethereum',
      'augmented-reality',
      'voice-interfaces',
    ],
  },
  {
    title: 'Life',
    curatedContentType: 'life-communities',
    communities: [
      'for-good',
      'mental-health',
      'dev-fit',
      'music',
      'photography',
      'tabletop-rpg',
      'gaming',
      'careers',
      'job-opportunities',
      'need-some-work',
    ],
  },
];
