// flow-typed signature: 229d182ee18954e4b62113295241ada3
// flow-typed version: <<STUB>>/abab_v1.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abab'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'abab' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abab/lib/atob' {
  declare module.exports: any;
}

declare module 'abab/lib/btoa' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abab/index' {
  declare module.exports: $Exports<'abab'>;
}
declare module 'abab/index.js' {
  declare module.exports: $Exports<'abab'>;
}
declare module 'abab/lib/atob.js' {
  declare module.exports: $Exports<'abab/lib/atob'>;
}
declare module 'abab/lib/btoa.js' {
  declare module.exports: $Exports<'abab/lib/btoa'>;
}
