// flow-typed signature: b79ee7ce2330ce3994e7c5eca830f792
// flow-typed version: <<STUB>>/algoliasearch_v^3.24.7/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'algoliasearch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'algoliasearch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'algoliasearch/dist/algoliasearch.angular' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.angular.min' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.jquery' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.jquery.min' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.min' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearch.parse' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearchLite' {
  declare module.exports: any;
}

declare module 'algoliasearch/dist/algoliasearchLite.min' {
  declare module.exports: any;
}

declare module 'algoliasearch/lite' {
  declare module.exports: any;
}

declare module 'algoliasearch/plugins/angular' {
  declare module.exports: any;
}

declare module 'algoliasearch/plugins/jquery' {
  declare module.exports: any;
}

declare module 'algoliasearch/reactnative' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/AlgoliaSearch' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/AlgoliaSearchCore' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/builds/algoliasearch.angular' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/builds/algoliasearch.jquery' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/builds/algoliasearch' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/builds/algoliasearchLite' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/createAlgoliasearch' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/get-document-protocol' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/inline-headers' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/jsonp-request' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/migration-layer/is-using-latest' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/migration-layer/load-v2' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/migration-layer/old-globals' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/browser/migration-layer/script' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/buildSearchMethod' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/clone' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/deprecate' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/deprecatedMessage' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/errors' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/exitPromise' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/Index' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/IndexBrowser' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/IndexCore' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/map' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/merge' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/omit' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/places' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/reactnative/builds/algoliasearch.reactnative' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/server/builds/AlgoliaSearchServer' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/server/builds/get-agent' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/server/builds/node' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/server/builds/parse' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/store' {
  declare module.exports: any;
}

declare module 'algoliasearch/src/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'algoliasearch/dist/algoliasearch.angular.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.angular'>;
}
declare module 'algoliasearch/dist/algoliasearch.angular.min.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.angular.min'>;
}
declare module 'algoliasearch/dist/algoliasearch.jquery.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.jquery'>;
}
declare module 'algoliasearch/dist/algoliasearch.jquery.min.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.jquery.min'>;
}
declare module 'algoliasearch/dist/algoliasearch.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch'>;
}
declare module 'algoliasearch/dist/algoliasearch.min.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.min'>;
}
declare module 'algoliasearch/dist/algoliasearch.parse.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearch.parse'>;
}
declare module 'algoliasearch/dist/algoliasearchLite.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearchLite'>;
}
declare module 'algoliasearch/dist/algoliasearchLite.min.js' {
  declare module.exports: $Exports<'algoliasearch/dist/algoliasearchLite.min'>;
}
declare module 'algoliasearch/index' {
  declare module.exports: $Exports<'algoliasearch'>;
}
declare module 'algoliasearch/index.js' {
  declare module.exports: $Exports<'algoliasearch'>;
}
declare module 'algoliasearch/lite.js' {
  declare module.exports: $Exports<'algoliasearch/lite'>;
}
declare module 'algoliasearch/plugins/angular.js' {
  declare module.exports: $Exports<'algoliasearch/plugins/angular'>;
}
declare module 'algoliasearch/plugins/jquery.js' {
  declare module.exports: $Exports<'algoliasearch/plugins/jquery'>;
}
declare module 'algoliasearch/reactnative.js' {
  declare module.exports: $Exports<'algoliasearch/reactnative'>;
}
declare module 'algoliasearch/src/AlgoliaSearch.js' {
  declare module.exports: $Exports<'algoliasearch/src/AlgoliaSearch'>;
}
declare module 'algoliasearch/src/AlgoliaSearchCore.js' {
  declare module.exports: $Exports<'algoliasearch/src/AlgoliaSearchCore'>;
}
declare module 'algoliasearch/src/browser/builds/algoliasearch.angular.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/builds/algoliasearch.angular'>;
}
declare module 'algoliasearch/src/browser/builds/algoliasearch.jquery.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/builds/algoliasearch.jquery'>;
}
declare module 'algoliasearch/src/browser/builds/algoliasearch.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/builds/algoliasearch'>;
}
declare module 'algoliasearch/src/browser/builds/algoliasearchLite.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/builds/algoliasearchLite'>;
}
declare module 'algoliasearch/src/browser/createAlgoliasearch.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/createAlgoliasearch'>;
}
declare module 'algoliasearch/src/browser/get-document-protocol.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/get-document-protocol'>;
}
declare module 'algoliasearch/src/browser/inline-headers.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/inline-headers'>;
}
declare module 'algoliasearch/src/browser/jsonp-request.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/jsonp-request'>;
}
declare module 'algoliasearch/src/browser/migration-layer/is-using-latest.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/migration-layer/is-using-latest'>;
}
declare module 'algoliasearch/src/browser/migration-layer/load-v2.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/migration-layer/load-v2'>;
}
declare module 'algoliasearch/src/browser/migration-layer/old-globals.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/migration-layer/old-globals'>;
}
declare module 'algoliasearch/src/browser/migration-layer/script.js' {
  declare module.exports: $Exports<'algoliasearch/src/browser/migration-layer/script'>;
}
declare module 'algoliasearch/src/buildSearchMethod.js' {
  declare module.exports: $Exports<'algoliasearch/src/buildSearchMethod'>;
}
declare module 'algoliasearch/src/clone.js' {
  declare module.exports: $Exports<'algoliasearch/src/clone'>;
}
declare module 'algoliasearch/src/deprecate.js' {
  declare module.exports: $Exports<'algoliasearch/src/deprecate'>;
}
declare module 'algoliasearch/src/deprecatedMessage.js' {
  declare module.exports: $Exports<'algoliasearch/src/deprecatedMessage'>;
}
declare module 'algoliasearch/src/errors.js' {
  declare module.exports: $Exports<'algoliasearch/src/errors'>;
}
declare module 'algoliasearch/src/exitPromise.js' {
  declare module.exports: $Exports<'algoliasearch/src/exitPromise'>;
}
declare module 'algoliasearch/src/Index.js' {
  declare module.exports: $Exports<'algoliasearch/src/Index'>;
}
declare module 'algoliasearch/src/IndexBrowser.js' {
  declare module.exports: $Exports<'algoliasearch/src/IndexBrowser'>;
}
declare module 'algoliasearch/src/IndexCore.js' {
  declare module.exports: $Exports<'algoliasearch/src/IndexCore'>;
}
declare module 'algoliasearch/src/map.js' {
  declare module.exports: $Exports<'algoliasearch/src/map'>;
}
declare module 'algoliasearch/src/merge.js' {
  declare module.exports: $Exports<'algoliasearch/src/merge'>;
}
declare module 'algoliasearch/src/omit.js' {
  declare module.exports: $Exports<'algoliasearch/src/omit'>;
}
declare module 'algoliasearch/src/places.js' {
  declare module.exports: $Exports<'algoliasearch/src/places'>;
}
declare module 'algoliasearch/src/reactnative/builds/algoliasearch.reactnative.js' {
  declare module.exports: $Exports<'algoliasearch/src/reactnative/builds/algoliasearch.reactnative'>;
}
declare module 'algoliasearch/src/server/builds/AlgoliaSearchServer.js' {
  declare module.exports: $Exports<'algoliasearch/src/server/builds/AlgoliaSearchServer'>;
}
declare module 'algoliasearch/src/server/builds/get-agent.js' {
  declare module.exports: $Exports<'algoliasearch/src/server/builds/get-agent'>;
}
declare module 'algoliasearch/src/server/builds/node.js' {
  declare module.exports: $Exports<'algoliasearch/src/server/builds/node'>;
}
declare module 'algoliasearch/src/server/builds/parse.js' {
  declare module.exports: $Exports<'algoliasearch/src/server/builds/parse'>;
}
declare module 'algoliasearch/src/store.js' {
  declare module.exports: $Exports<'algoliasearch/src/store'>;
}
declare module 'algoliasearch/src/version.js' {
  declare module.exports: $Exports<'algoliasearch/src/version'>;
}
