// flow-typed signature: fed729f4c8392f815391ae2316878ed8
// flow-typed version: <<STUB>>/amplitude_v3.5.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'amplitude'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'amplitude' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'amplitude/amplitude' {
  declare module.exports: any;
}

// Filename aliases
declare module 'amplitude/amplitude.js' {
  declare module.exports: $Exports<'amplitude/amplitude'>;
}
