// flow-typed signature: e347c1991b58f57957a33dd89d2c6203
// flow-typed version: <<STUB>>/apollo-engine_v^0.8.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-engine/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/middleware' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/connect' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/engine' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/express' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/hapi' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/koa' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/micro' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/schema' {
  declare module.exports: any;
}

declare module 'apollo-engine/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-engine/lib/index.js' {
  declare module.exports: $Exports<'apollo-engine/lib/index'>;
}
declare module 'apollo-engine/lib/middleware.js' {
  declare module.exports: $Exports<'apollo-engine/lib/middleware'>;
}
declare module 'apollo-engine/test/connect.js' {
  declare module.exports: $Exports<'apollo-engine/test/connect'>;
}
declare module 'apollo-engine/test/engine.js' {
  declare module.exports: $Exports<'apollo-engine/test/engine'>;
}
declare module 'apollo-engine/test/express.js' {
  declare module.exports: $Exports<'apollo-engine/test/express'>;
}
declare module 'apollo-engine/test/hapi.js' {
  declare module.exports: $Exports<'apollo-engine/test/hapi'>;
}
declare module 'apollo-engine/test/koa.js' {
  declare module.exports: $Exports<'apollo-engine/test/koa'>;
}
declare module 'apollo-engine/test/micro.js' {
  declare module.exports: $Exports<'apollo-engine/test/micro'>;
}
declare module 'apollo-engine/test/schema.js' {
  declare module.exports: $Exports<'apollo-engine/test/schema'>;
}
declare module 'apollo-engine/test/test.js' {
  declare module.exports: $Exports<'apollo-engine/test/test'>;
}
