// flow-typed signature: 4e870a20f8b27e51ad50130782138d07
// flow-typed version: <<STUB>>/apollo-cache-inmemory_v1.1.5/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-cache-inmemory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-cache-inmemory' {
  declare module.exports: any;
}
