// flow-typed signature: 314acb3e039992312b50164d1bd3ee7c
// flow-typed version: <<STUB>>/apollo-engine_v0.5.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-engine'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-engine' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-engine/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-engine/lib/middleware' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-engine/lib/index.js' {
  declare module.exports: $Exports<'apollo-engine/lib/index'>;
}
declare module 'apollo-engine/lib/middleware.js' {
  declare module.exports: $Exports<'apollo-engine/lib/middleware'>;
}
