// flow-typed signature: 117ba9d930921f50a85cdfae1b01d88f
// flow-typed version: <<STUB>>/apollo-upload-client_v^5.1.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-client/dist/apollo-upload-client' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/dist/apollo-upload-client.module' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/src/batched-network-interface' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/src/index' {
  declare module.exports: any;
}

declare module 'apollo-upload-client/src/network-interface' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-client/dist/apollo-upload-client.js' {
  declare module.exports: $Exports<'apollo-upload-client/dist/apollo-upload-client'>;
}
declare module 'apollo-upload-client/dist/apollo-upload-client.module.js' {
  declare module.exports: $Exports<'apollo-upload-client/dist/apollo-upload-client.module'>;
}
declare module 'apollo-upload-client/src/batched-network-interface.js' {
  declare module.exports: $Exports<'apollo-upload-client/src/batched-network-interface'>;
}
declare module 'apollo-upload-client/src/index.js' {
  declare module.exports: $Exports<'apollo-upload-client/src/index'>;
}
declare module 'apollo-upload-client/src/network-interface.js' {
  declare module.exports: $Exports<'apollo-upload-client/src/network-interface'>;
}
