// flow-typed signature: 24e78321d1ce97826d55241446c65e89
// flow-typed version: <<STUB>>/apollo-server-plugin-response-cache_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-plugin-response-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-plugin-response-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache' {
  declare module.exports: any;
}

declare module 'apollo-server-plugin-response-cache/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js' {
  declare module.exports: $Exports<'apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache'>;
}
declare module 'apollo-server-plugin-response-cache/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-plugin-response-cache/dist/index'>;
}
