// flow-typed signature: f10de48a7e33496e4a9ec4960ee54eeb
// flow-typed version: <<STUB>>/apollo-upload-server_v^2.0.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-upload-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-upload-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-upload-server/dist/apollo-upload-server' {
  declare module.exports: any;
}

declare module 'apollo-upload-server/dist/apollo-upload-server.module' {
  declare module.exports: any;
}

declare module 'apollo-upload-server/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-upload-server/dist/apollo-upload-server.js' {
  declare module.exports: $Exports<'apollo-upload-server/dist/apollo-upload-server'>;
}
declare module 'apollo-upload-server/dist/apollo-upload-server.module.js' {
  declare module.exports: $Exports<'apollo-upload-server/dist/apollo-upload-server.module'>;
}
declare module 'apollo-upload-server/src/index.js' {
  declare module.exports: $Exports<'apollo-upload-server/src/index'>;
}
