// flow-typed signature: 2d49bd60960076967702ccedf0db590b
// flow-typed version: <<STUB>>/apollo-utilities_v1.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-utilities'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-utilities' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-utilities/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/directives' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/fragments' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/getFromAST' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/storeUtils' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/transform' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/assign' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/cloneDeep' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/environment' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/errorHandling' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/isEqual' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/maybeDeepFreeze' {
  declare module.exports: any;
}

declare module 'apollo-utilities/lib/util/warnOnce' {
  declare module.exports: any;
}

declare module 'apollo-utilities/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-utilities/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/bundle.umd'>;
}
declare module 'apollo-utilities/lib/directives.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/directives'>;
}
declare module 'apollo-utilities/lib/fragments.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/fragments'>;
}
declare module 'apollo-utilities/lib/getFromAST.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/getFromAST'>;
}
declare module 'apollo-utilities/lib/index.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/index'>;
}
declare module 'apollo-utilities/lib/storeUtils.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/storeUtils'>;
}
declare module 'apollo-utilities/lib/transform.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/transform'>;
}
declare module 'apollo-utilities/lib/util/assign.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/assign'>;
}
declare module 'apollo-utilities/lib/util/cloneDeep.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/cloneDeep'>;
}
declare module 'apollo-utilities/lib/util/environment.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/environment'>;
}
declare module 'apollo-utilities/lib/util/errorHandling.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/errorHandling'>;
}
declare module 'apollo-utilities/lib/util/isEqual.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/isEqual'>;
}
declare module 'apollo-utilities/lib/util/maybeDeepFreeze.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/maybeDeepFreeze'>;
}
declare module 'apollo-utilities/lib/util/warnOnce.js' {
  declare module.exports: $Exports<'apollo-utilities/lib/util/warnOnce'>;
}
declare module 'apollo-utilities/rollup.config.js' {
  declare module.exports: $Exports<'apollo-utilities/rollup.config'>;
}
