// flow-typed signature: 61e2076f557fee75ba8e0dd7a7f21ae8
// flow-typed version: <<STUB>>/apollo-link-schema_v1.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-schema/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-schema/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-schema/lib/schemaLink' {
  declare module.exports: any;
}

declare module 'apollo-link-schema/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-schema/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-schema/lib/bundle.umd'>;
}
declare module 'apollo-link-schema/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-schema/lib/index'>;
}
declare module 'apollo-link-schema/lib/schemaLink.js' {
  declare module.exports: $Exports<'apollo-link-schema/lib/schemaLink'>;
}
declare module 'apollo-link-schema/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-schema/rollup.config'>;
}
