// flow-typed signature: 0b56a0e3e55fd528e940b9d96f25c05e
// flow-typed version: <<STUB>>/apollo-client_v2.x/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-client/ApolloClient' {
  declare module.exports: any;
}

declare module 'apollo-client/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-client/core/networkStatus' {
  declare module.exports: any;
}

declare module 'apollo-client/core/ObservableQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/core/QueryManager' {
  declare module.exports: any;
}

declare module 'apollo-client/core/types' {
  declare module.exports: any;
}

declare module 'apollo-client/core/watchQueryOptions' {
  declare module.exports: any;
}

declare module 'apollo-client/data/mutations' {
  declare module.exports: any;
}

declare module 'apollo-client/data/queries' {
  declare module.exports: any;
}

declare module 'apollo-client/data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/errors/ApolloError' {
  declare module.exports: any;
}

declare module 'apollo-client/scheduler/scheduler' {
  declare module.exports: any;
}

declare module 'apollo-client/util/Observable' {
  declare module.exports: any;
}

declare module 'apollo-client/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-client/ApolloClient.js' {
  declare module.exports: $Exports<'apollo-client/ApolloClient'>;
}
declare module 'apollo-client/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-client/bundle.umd'>;
}
declare module 'apollo-client/core/networkStatus.js' {
  declare module.exports: $Exports<'apollo-client/core/networkStatus'>;
}
declare module 'apollo-client/core/ObservableQuery.js' {
  declare module.exports: $Exports<'apollo-client/core/ObservableQuery'>;
}
declare module 'apollo-client/core/QueryManager.js' {
  declare module.exports: $Exports<'apollo-client/core/QueryManager'>;
}
declare module 'apollo-client/core/types.js' {
  declare module.exports: $Exports<'apollo-client/core/types'>;
}
declare module 'apollo-client/core/watchQueryOptions.js' {
  declare module.exports: $Exports<'apollo-client/core/watchQueryOptions'>;
}
declare module 'apollo-client/data/mutations.js' {
  declare module.exports: $Exports<'apollo-client/data/mutations'>;
}
declare module 'apollo-client/data/queries.js' {
  declare module.exports: $Exports<'apollo-client/data/queries'>;
}
declare module 'apollo-client/data/store.js' {
  declare module.exports: $Exports<'apollo-client/data/store'>;
}
declare module 'apollo-client/errors/ApolloError.js' {
  declare module.exports: $Exports<'apollo-client/errors/ApolloError'>;
}
declare module 'apollo-client/index' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/index.js' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/scheduler/scheduler.js' {
  declare module.exports: $Exports<'apollo-client/scheduler/scheduler'>;
}
declare module 'apollo-client/util/Observable.js' {
  declare module.exports: $Exports<'apollo-client/util/Observable'>;
}
declare module 'apollo-client/version.js' {
  declare module.exports: $Exports<'apollo-client/version'>;
}
