// flow-typed signature: ec1561a0a232d76f4752b95714dc3ead
// flow-typed version: <<STUB>>/apollo-client_v2.2.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-client/actions' {
  declare module.exports: any;
}

declare module 'apollo-client/apollo.umd' {
  declare module.exports: any;
}

declare module 'apollo-client/ApolloClient' {
  declare module.exports: any;
}

declare module 'apollo-client/core/ObservableQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/core/QueryManager' {
  declare module.exports: any;
}

declare module 'apollo-client/core/types' {
  declare module.exports: any;
}

declare module 'apollo-client/core/watchQueryOptions' {
  declare module.exports: any;
}

declare module 'apollo-client/data/fragmentMatcher' {
  declare module.exports: any;
}

declare module 'apollo-client/data/fragmentMatcherIntrospectionQuery' {
  declare module.exports: any;
}

declare module 'apollo-client/data/mutationResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/proxy' {
  declare module.exports: any;
}

declare module 'apollo-client/data/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-client/data/replaceQueryResults' {
  declare module.exports: any;
}

declare module 'apollo-client/data/resultReducers' {
  declare module.exports: any;
}

declare module 'apollo-client/data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/data/storeUtils' {
  declare module.exports: any;
}

declare module 'apollo-client/data/writeToStore' {
  declare module.exports: any;
}

declare module 'apollo-client/errors/ApolloError' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/benchmark_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/chai_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/chai-as-promised_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/lodash_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/node_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/promises-a-plus_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/@types/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/benchmark_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/browserify_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/chai_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/chai-as-promised_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/colors_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/concurrently_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/es6-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/fetch-mock_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/graphql-anywhere_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/graphql-tag_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/grunt_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/grunt-tslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/gzip-size_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/isomorphic-fetch_v2.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/minimist_v1.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/nodemon_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/pretty-bytes_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/remap-istanbul_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/request_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/rxjs_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/source-map-support_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/symbol-observable_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/tslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/typescript_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/uglify-js_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/webpack-bundle-analyzer_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/flow-typed/npm/whatwg-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module 'apollo-client/mutations/store' {
  declare module.exports: any;
}

declare module 'apollo-client/optimistic-data/store' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/directives' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/getFromAST' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/networkStatus' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/queryTransform' {
  declare module.exports: any;
}

declare module 'apollo-client/queries/store' {
  declare module.exports: any;
}

declare module 'apollo-client/scheduler/scheduler' {
  declare module.exports: any;
}

declare module 'apollo-client/store' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/afterware' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/batchedNetworkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/batching' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/Deduplicator' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/middleware' {
  declare module.exports: any;
}

declare module 'apollo-client/transport/networkInterface' {
  declare module.exports: any;
}

declare module 'apollo-client/util/assign' {
  declare module.exports: any;
}

declare module 'apollo-client/util/cloneDeep' {
  declare module.exports: any;
}

declare module 'apollo-client/util/environment' {
  declare module.exports: any;
}

declare module 'apollo-client/util/errorHandling' {
  declare module.exports: any;
}

declare module 'apollo-client/util/isEqual' {
  declare module.exports: any;
}

declare module 'apollo-client/util/maybeDeepFreeze' {
  declare module.exports: any;
}

declare module 'apollo-client/util/Observable' {
  declare module.exports: any;
}

declare module 'apollo-client/util/warnOnce' {
  declare module.exports: any;
}

declare module 'apollo-client/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-client/actions.js' {
  declare module.exports: $Exports<'apollo-client/actions'>;
}
declare module 'apollo-client/apollo.umd.js' {
  declare module.exports: $Exports<'apollo-client/apollo.umd'>;
}
declare module 'apollo-client/ApolloClient.js' {
  declare module.exports: $Exports<'apollo-client/ApolloClient'>;
}
declare module 'apollo-client/core/ObservableQuery.js' {
  declare module.exports: $Exports<'apollo-client/core/ObservableQuery'>;
}
declare module 'apollo-client/core/QueryManager.js' {
  declare module.exports: $Exports<'apollo-client/core/QueryManager'>;
}
declare module 'apollo-client/core/types.js' {
  declare module.exports: $Exports<'apollo-client/core/types'>;
}
declare module 'apollo-client/core/watchQueryOptions.js' {
  declare module.exports: $Exports<'apollo-client/core/watchQueryOptions'>;
}
declare module 'apollo-client/data/fragmentMatcher.js' {
  declare module.exports: $Exports<'apollo-client/data/fragmentMatcher'>;
}
declare module 'apollo-client/data/fragmentMatcherIntrospectionQuery.js' {
  declare module.exports: $Exports<'apollo-client/data/fragmentMatcherIntrospectionQuery'>;
}
declare module 'apollo-client/data/mutationResults.js' {
  declare module.exports: $Exports<'apollo-client/data/mutationResults'>;
}
declare module 'apollo-client/data/proxy.js' {
  declare module.exports: $Exports<'apollo-client/data/proxy'>;
}
declare module 'apollo-client/data/readFromStore.js' {
  declare module.exports: $Exports<'apollo-client/data/readFromStore'>;
}
declare module 'apollo-client/data/replaceQueryResults.js' {
  declare module.exports: $Exports<'apollo-client/data/replaceQueryResults'>;
}
declare module 'apollo-client/data/resultReducers.js' {
  declare module.exports: $Exports<'apollo-client/data/resultReducers'>;
}
declare module 'apollo-client/data/store.js' {
  declare module.exports: $Exports<'apollo-client/data/store'>;
}
declare module 'apollo-client/data/storeUtils.js' {
  declare module.exports: $Exports<'apollo-client/data/storeUtils'>;
}
declare module 'apollo-client/data/writeToStore.js' {
  declare module.exports: $Exports<'apollo-client/data/writeToStore'>;
}
declare module 'apollo-client/errors/ApolloError.js' {
  declare module.exports: $Exports<'apollo-client/errors/ApolloError'>;
}
declare module 'apollo-client/flow-typed/npm/@types/benchmark_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/benchmark_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/chai_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/chai_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/chai-as-promised_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/chai-as-promised_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/lodash_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/lodash_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/mocha_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/node_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/node_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/promises-a-plus_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/promises-a-plus_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/@types/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/@types/sinon_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/benchmark_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/benchmark_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/browserify_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/browserify_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/chai_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/chai_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/chai-as-promised_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/chai-as-promised_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/colors_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/colors_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/concurrently_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/concurrently_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/es6-promise_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/es6-promise_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/fetch-mock_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/fetch-mock_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/graphql-anywhere_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/graphql-anywhere_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/graphql-tag_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/graphql-tag_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/grunt_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/grunt_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/grunt-tslint_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/grunt-tslint_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/gzip-size_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/gzip-size_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/isomorphic-fetch_v2.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/isomorphic-fetch_v2.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/istanbul_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/minimist_v1.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/minimist_v1.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/mocha_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/nodemon_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/nodemon_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/pretty-bytes_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/pretty-bytes_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/remap-istanbul_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/remap-istanbul_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/request_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/request_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/rxjs_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/rxjs_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/sinon_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/source-map-support_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/source-map-support_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/symbol-observable_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/symbol-observable_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/tslint_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/tslint_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/typescript_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/typescript_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/uglify-js_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/uglify-js_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/webpack-bundle-analyzer_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/webpack-bundle-analyzer_vx.x.x'>;
}
declare module 'apollo-client/flow-typed/npm/whatwg-fetch_vx.x.x.js' {
  declare module.exports: $Exports<'apollo-client/flow-typed/npm/whatwg-fetch_vx.x.x'>;
}
declare module 'apollo-client/index' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/index.js' {
  declare module.exports: $Exports<'apollo-client'>;
}
declare module 'apollo-client/mutations/store.js' {
  declare module.exports: $Exports<'apollo-client/mutations/store'>;
}
declare module 'apollo-client/optimistic-data/store.js' {
  declare module.exports: $Exports<'apollo-client/optimistic-data/store'>;
}
declare module 'apollo-client/queries/directives.js' {
  declare module.exports: $Exports<'apollo-client/queries/directives'>;
}
declare module 'apollo-client/queries/getFromAST.js' {
  declare module.exports: $Exports<'apollo-client/queries/getFromAST'>;
}
declare module 'apollo-client/queries/networkStatus.js' {
  declare module.exports: $Exports<'apollo-client/queries/networkStatus'>;
}
declare module 'apollo-client/queries/queryTransform.js' {
  declare module.exports: $Exports<'apollo-client/queries/queryTransform'>;
}
declare module 'apollo-client/queries/store.js' {
  declare module.exports: $Exports<'apollo-client/queries/store'>;
}
declare module 'apollo-client/scheduler/scheduler.js' {
  declare module.exports: $Exports<'apollo-client/scheduler/scheduler'>;
}
declare module 'apollo-client/store.js' {
  declare module.exports: $Exports<'apollo-client/store'>;
}
declare module 'apollo-client/transport/afterware.js' {
  declare module.exports: $Exports<'apollo-client/transport/afterware'>;
}
declare module 'apollo-client/transport/batchedNetworkInterface.js' {
  declare module.exports: $Exports<'apollo-client/transport/batchedNetworkInterface'>;
}
declare module 'apollo-client/transport/batching.js' {
  declare module.exports: $Exports<'apollo-client/transport/batching'>;
}
declare module 'apollo-client/transport/Deduplicator.js' {
  declare module.exports: $Exports<'apollo-client/transport/Deduplicator'>;
}
declare module 'apollo-client/transport/middleware.js' {
  declare module.exports: $Exports<'apollo-client/transport/middleware'>;
}
declare module 'apollo-client/transport/networkInterface.js' {
  declare module.exports: $Exports<'apollo-client/transport/networkInterface'>;
}
declare module 'apollo-client/util/assign.js' {
  declare module.exports: $Exports<'apollo-client/util/assign'>;
}
declare module 'apollo-client/util/cloneDeep.js' {
  declare module.exports: $Exports<'apollo-client/util/cloneDeep'>;
}
declare module 'apollo-client/util/environment.js' {
  declare module.exports: $Exports<'apollo-client/util/environment'>;
}
declare module 'apollo-client/util/errorHandling.js' {
  declare module.exports: $Exports<'apollo-client/util/errorHandling'>;
}
declare module 'apollo-client/util/isEqual.js' {
  declare module.exports: $Exports<'apollo-client/util/isEqual'>;
}
declare module 'apollo-client/util/maybeDeepFreeze.js' {
  declare module.exports: $Exports<'apollo-client/util/maybeDeepFreeze'>;
}
declare module 'apollo-client/util/Observable.js' {
  declare module.exports: $Exports<'apollo-client/util/Observable'>;
}
declare module 'apollo-client/util/warnOnce.js' {
  declare module.exports: $Exports<'apollo-client/util/warnOnce'>;
}
declare module 'apollo-client/version.js' {
  declare module.exports: $Exports<'apollo-client/version'>;
}
