// flow-typed signature: 458f54b9229cd74dc54679aad2fb6f13
// flow-typed version: <<STUB>>/b2a_v1.0.10/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'b2a'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'b2a' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'b2a/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'b2a/lib/index.js' {
  declare module.exports: $Exports<'b2a/lib/index'>;
}
