// flow-typed signature: 498068283d7cb370197e7324b3db5923
// flow-typed version: <<STUB>>/babel-plugin-transform-async-generator-functions_v^6.24.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-async-generator-functions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-async-generator-functions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-async-generator-functions/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-async-generator-functions/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-async-generator-functions/lib/index'>;
}
