// flow-typed signature: 33872ebde21071c44e9745e044f4a43f
// flow-typed version: <<STUB>>/backpack-core_v^0.4.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backpack-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'backpack-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backpack-core/babel' {
  declare module.exports: any;
}

declare module 'backpack-core/config/paths' {
  declare module.exports: any;
}

declare module 'backpack-core/config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backpack-core/babel.js' {
  declare module.exports: $Exports<'backpack-core/babel'>;
}
declare module 'backpack-core/config/paths.js' {
  declare module.exports: $Exports<'backpack-core/config/paths'>;
}
declare module 'backpack-core/config/webpack.config.js' {
  declare module.exports: $Exports<'backpack-core/config/webpack.config'>;
}
