// flow-typed signature: 191b454033816150d2194336e74fbe32
// flow-typed version: <<STUB>>/bad-words_v^1.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bad-words'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bad-words' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bad-words/lib/badwords' {
  declare module.exports: any;
}

declare module 'bad-words/test/addWords' {
  declare module.exports: any;
}

declare module 'bad-words/test/filter' {
  declare module.exports: any;
}

declare module 'bad-words/test/isProfane' {
  declare module.exports: any;
}

declare module 'bad-words/test/removeWords' {
  declare module.exports: any;
}

declare module 'bad-words/test/replaceWord' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bad-words/lib/badwords.js' {
  declare module.exports: $Exports<'bad-words/lib/badwords'>;
}
declare module 'bad-words/test/addWords.js' {
  declare module.exports: $Exports<'bad-words/test/addWords'>;
}
declare module 'bad-words/test/filter.js' {
  declare module.exports: $Exports<'bad-words/test/filter'>;
}
declare module 'bad-words/test/isProfane.js' {
  declare module.exports: $Exports<'bad-words/test/isProfane'>;
}
declare module 'bad-words/test/removeWords.js' {
  declare module.exports: $Exports<'bad-words/test/removeWords'>;
}
declare module 'bad-words/test/replaceWord.js' {
  declare module.exports: $Exports<'bad-words/test/replaceWord'>;
}
