// flow-typed signature: fd6015492cc31b2750e3b5e1b048858f
// flow-typed version: <<STUB>>/bluebird_v3.5.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bluebird'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bluebird' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bluebird/js/browser/bluebird.core' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird.core.min' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/browser/bluebird.min' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/any' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/assert' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/async' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/bind' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/bluebird' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/call_get' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/cancel' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/catch_filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/context' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/debuggability' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/direct_resolve' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/each' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/errors' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/es5' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/filter' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/finally' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/generators' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/join' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/map' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/method' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/nodeback' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/nodeify' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promise_array' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promise' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/promisify' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/props' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/queue' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/race' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/reduce' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/schedule' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/settle' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/some' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/synchronous_inspection' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/thenables' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/timers' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/using' {
  declare module.exports: any;
}

declare module 'bluebird/js/release/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bluebird/js/browser/bluebird.core.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird.core'>;
}
declare module 'bluebird/js/browser/bluebird.core.min.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird.core.min'>;
}
declare module 'bluebird/js/browser/bluebird.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird'>;
}
declare module 'bluebird/js/browser/bluebird.min.js' {
  declare module.exports: $Exports<'bluebird/js/browser/bluebird.min'>;
}
declare module 'bluebird/js/release/any.js' {
  declare module.exports: $Exports<'bluebird/js/release/any'>;
}
declare module 'bluebird/js/release/assert.js' {
  declare module.exports: $Exports<'bluebird/js/release/assert'>;
}
declare module 'bluebird/js/release/async.js' {
  declare module.exports: $Exports<'bluebird/js/release/async'>;
}
declare module 'bluebird/js/release/bind.js' {
  declare module.exports: $Exports<'bluebird/js/release/bind'>;
}
declare module 'bluebird/js/release/bluebird.js' {
  declare module.exports: $Exports<'bluebird/js/release/bluebird'>;
}
declare module 'bluebird/js/release/call_get.js' {
  declare module.exports: $Exports<'bluebird/js/release/call_get'>;
}
declare module 'bluebird/js/release/cancel.js' {
  declare module.exports: $Exports<'bluebird/js/release/cancel'>;
}
declare module 'bluebird/js/release/catch_filter.js' {
  declare module.exports: $Exports<'bluebird/js/release/catch_filter'>;
}
declare module 'bluebird/js/release/context.js' {
  declare module.exports: $Exports<'bluebird/js/release/context'>;
}
declare module 'bluebird/js/release/debuggability.js' {
  declare module.exports: $Exports<'bluebird/js/release/debuggability'>;
}
declare module 'bluebird/js/release/direct_resolve.js' {
  declare module.exports: $Exports<'bluebird/js/release/direct_resolve'>;
}
declare module 'bluebird/js/release/each.js' {
  declare module.exports: $Exports<'bluebird/js/release/each'>;
}
declare module 'bluebird/js/release/errors.js' {
  declare module.exports: $Exports<'bluebird/js/release/errors'>;
}
declare module 'bluebird/js/release/es5.js' {
  declare module.exports: $Exports<'bluebird/js/release/es5'>;
}
declare module 'bluebird/js/release/filter.js' {
  declare module.exports: $Exports<'bluebird/js/release/filter'>;
}
declare module 'bluebird/js/release/finally.js' {
  declare module.exports: $Exports<'bluebird/js/release/finally'>;
}
declare module 'bluebird/js/release/generators.js' {
  declare module.exports: $Exports<'bluebird/js/release/generators'>;
}
declare module 'bluebird/js/release/join.js' {
  declare module.exports: $Exports<'bluebird/js/release/join'>;
}
declare module 'bluebird/js/release/map.js' {
  declare module.exports: $Exports<'bluebird/js/release/map'>;
}
declare module 'bluebird/js/release/method.js' {
  declare module.exports: $Exports<'bluebird/js/release/method'>;
}
declare module 'bluebird/js/release/nodeback.js' {
  declare module.exports: $Exports<'bluebird/js/release/nodeback'>;
}
declare module 'bluebird/js/release/nodeify.js' {
  declare module.exports: $Exports<'bluebird/js/release/nodeify'>;
}
declare module 'bluebird/js/release/promise_array.js' {
  declare module.exports: $Exports<'bluebird/js/release/promise_array'>;
}
declare module 'bluebird/js/release/promise.js' {
  declare module.exports: $Exports<'bluebird/js/release/promise'>;
}
declare module 'bluebird/js/release/promisify.js' {
  declare module.exports: $Exports<'bluebird/js/release/promisify'>;
}
declare module 'bluebird/js/release/props.js' {
  declare module.exports: $Exports<'bluebird/js/release/props'>;
}
declare module 'bluebird/js/release/queue.js' {
  declare module.exports: $Exports<'bluebird/js/release/queue'>;
}
declare module 'bluebird/js/release/race.js' {
  declare module.exports: $Exports<'bluebird/js/release/race'>;
}
declare module 'bluebird/js/release/reduce.js' {
  declare module.exports: $Exports<'bluebird/js/release/reduce'>;
}
declare module 'bluebird/js/release/schedule.js' {
  declare module.exports: $Exports<'bluebird/js/release/schedule'>;
}
declare module 'bluebird/js/release/settle.js' {
  declare module.exports: $Exports<'bluebird/js/release/settle'>;
}
declare module 'bluebird/js/release/some.js' {
  declare module.exports: $Exports<'bluebird/js/release/some'>;
}
declare module 'bluebird/js/release/synchronous_inspection.js' {
  declare module.exports: $Exports<'bluebird/js/release/synchronous_inspection'>;
}
declare module 'bluebird/js/release/thenables.js' {
  declare module.exports: $Exports<'bluebird/js/release/thenables'>;
}
declare module 'bluebird/js/release/timers.js' {
  declare module.exports: $Exports<'bluebird/js/release/timers'>;
}
declare module 'bluebird/js/release/using.js' {
  declare module.exports: $Exports<'bluebird/js/release/using'>;
}
declare module 'bluebird/js/release/util.js' {
  declare module.exports: $Exports<'bluebird/js/release/util'>;
}
