// flow-typed signature: e976979fb2407edbf63d986d23ef3257
// flow-typed version: <<STUB>>/bull_v3.0.0-rc.8/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bull'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bull' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bull/examples/cluster-queue' {
  declare module.exports: any;
}

declare module 'bull/examples/message' {
  declare module.exports: any;
}

declare module 'bull/examples/state' {
  declare module.exports: any;
}

declare module 'bull/lib/commands/index' {
  declare module.exports: any;
}

declare module 'bull/lib/errors' {
  declare module.exports: any;
}

declare module 'bull/lib/getters' {
  declare module.exports: any;
}

declare module 'bull/lib/job' {
  declare module.exports: any;
}

declare module 'bull/lib/queue' {
  declare module.exports: any;
}

declare module 'bull/lib/repeatable' {
  declare module.exports: any;
}

declare module 'bull/lib/schedule' {
  declare module.exports: any;
}

declare module 'bull/lib/scripts' {
  declare module.exports: any;
}

declare module 'bull/lib/timer-manager' {
  declare module.exports: any;
}

declare module 'bull/lib/utils' {
  declare module.exports: any;
}

declare module 'bull/lib/worker' {
  declare module.exports: any;
}

declare module 'bull/test/cluster_worker' {
  declare module.exports: any;
}

declare module 'bull/test/test_cluster' {
  declare module.exports: any;
}

declare module 'bull/test/test_connection' {
  declare module.exports: any;
}

declare module 'bull/test/test_job' {
  declare module.exports: any;
}

declare module 'bull/test/test_queue' {
  declare module.exports: any;
}

declare module 'bull/test/test_repeat' {
  declare module.exports: any;
}

declare module 'bull/test/test_worker' {
  declare module.exports: any;
}

declare module 'bull/test/utils' {
  declare module.exports: any;
}

declare module 'bull/Untitled-1' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bull/examples/cluster-queue.js' {
  declare module.exports: $Exports<'bull/examples/cluster-queue'>;
}
declare module 'bull/examples/message.js' {
  declare module.exports: $Exports<'bull/examples/message'>;
}
declare module 'bull/examples/state.js' {
  declare module.exports: $Exports<'bull/examples/state'>;
}
declare module 'bull/lib/commands/index.js' {
  declare module.exports: $Exports<'bull/lib/commands/index'>;
}
declare module 'bull/lib/errors.js' {
  declare module.exports: $Exports<'bull/lib/errors'>;
}
declare module 'bull/lib/getters.js' {
  declare module.exports: $Exports<'bull/lib/getters'>;
}
declare module 'bull/lib/job.js' {
  declare module.exports: $Exports<'bull/lib/job'>;
}
declare module 'bull/lib/queue.js' {
  declare module.exports: $Exports<'bull/lib/queue'>;
}
declare module 'bull/lib/repeatable.js' {
  declare module.exports: $Exports<'bull/lib/repeatable'>;
}
declare module 'bull/lib/schedule.js' {
  declare module.exports: $Exports<'bull/lib/schedule'>;
}
declare module 'bull/lib/scripts.js' {
  declare module.exports: $Exports<'bull/lib/scripts'>;
}
declare module 'bull/lib/timer-manager.js' {
  declare module.exports: $Exports<'bull/lib/timer-manager'>;
}
declare module 'bull/lib/utils.js' {
  declare module.exports: $Exports<'bull/lib/utils'>;
}
declare module 'bull/lib/worker.js' {
  declare module.exports: $Exports<'bull/lib/worker'>;
}
declare module 'bull/test/cluster_worker.js' {
  declare module.exports: $Exports<'bull/test/cluster_worker'>;
}
declare module 'bull/test/test_cluster.js' {
  declare module.exports: $Exports<'bull/test/test_cluster'>;
}
declare module 'bull/test/test_connection.js' {
  declare module.exports: $Exports<'bull/test/test_connection'>;
}
declare module 'bull/test/test_job.js' {
  declare module.exports: $Exports<'bull/test/test_job'>;
}
declare module 'bull/test/test_queue.js' {
  declare module.exports: $Exports<'bull/test/test_queue'>;
}
declare module 'bull/test/test_repeat.js' {
  declare module.exports: $Exports<'bull/test/test_repeat'>;
}
declare module 'bull/test/test_worker.js' {
  declare module.exports: $Exports<'bull/test/test_worker'>;
}
declare module 'bull/test/utils.js' {
  declare module.exports: $Exports<'bull/test/utils'>;
}
declare module 'bull/Untitled-1.js' {
  declare module.exports: $Exports<'bull/Untitled-1'>;
}
