// flow-typed signature: 75dc078152e6e97382b34bbe99dcaf4f
// flow-typed version: <<STUB>>/cryptr_v3.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cryptr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cryptr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cryptr/tests/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cryptr/index' {
  declare module.exports: $Exports<'cryptr'>;
}
declare module 'cryptr/index.js' {
  declare module.exports: $Exports<'cryptr'>;
}
declare module 'cryptr/tests/index.js' {
  declare module.exports: $Exports<'cryptr/tests/index'>;
}
