// flow-typed signature: 8a1fe35a0f1cbef7caf7734f328697de
// flow-typed version: <<STUB>>/d3-array_v^1.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-array/build/d3-array' {
  declare module.exports: any;
}

declare module 'd3-array/build/d3-array.min' {
  declare module.exports: any;
}

declare module 'd3-array/src/array' {
  declare module.exports: any;
}

declare module 'd3-array/src/ascending' {
  declare module.exports: any;
}

declare module 'd3-array/src/bisect' {
  declare module.exports: any;
}

declare module 'd3-array/src/bisector' {
  declare module.exports: any;
}

declare module 'd3-array/src/constant' {
  declare module.exports: any;
}

declare module 'd3-array/src/cross' {
  declare module.exports: any;
}

declare module 'd3-array/src/descending' {
  declare module.exports: any;
}

declare module 'd3-array/src/deviation' {
  declare module.exports: any;
}

declare module 'd3-array/src/extent' {
  declare module.exports: any;
}

declare module 'd3-array/src/histogram' {
  declare module.exports: any;
}

declare module 'd3-array/src/identity' {
  declare module.exports: any;
}

declare module 'd3-array/src/max' {
  declare module.exports: any;
}

declare module 'd3-array/src/mean' {
  declare module.exports: any;
}

declare module 'd3-array/src/median' {
  declare module.exports: any;
}

declare module 'd3-array/src/merge' {
  declare module.exports: any;
}

declare module 'd3-array/src/min' {
  declare module.exports: any;
}

declare module 'd3-array/src/number' {
  declare module.exports: any;
}

declare module 'd3-array/src/pairs' {
  declare module.exports: any;
}

declare module 'd3-array/src/permute' {
  declare module.exports: any;
}

declare module 'd3-array/src/quantile' {
  declare module.exports: any;
}

declare module 'd3-array/src/range' {
  declare module.exports: any;
}

declare module 'd3-array/src/scan' {
  declare module.exports: any;
}

declare module 'd3-array/src/shuffle' {
  declare module.exports: any;
}

declare module 'd3-array/src/sum' {
  declare module.exports: any;
}

declare module 'd3-array/src/threshold/freedmanDiaconis' {
  declare module.exports: any;
}

declare module 'd3-array/src/threshold/scott' {
  declare module.exports: any;
}

declare module 'd3-array/src/threshold/sturges' {
  declare module.exports: any;
}

declare module 'd3-array/src/ticks' {
  declare module.exports: any;
}

declare module 'd3-array/src/transpose' {
  declare module.exports: any;
}

declare module 'd3-array/src/variance' {
  declare module.exports: any;
}

declare module 'd3-array/src/zip' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-array/build/d3-array.js' {
  declare module.exports: $Exports<'d3-array/build/d3-array'>;
}
declare module 'd3-array/build/d3-array.min.js' {
  declare module.exports: $Exports<'d3-array/build/d3-array.min'>;
}
declare module 'd3-array/index' {
  declare module.exports: $Exports<'d3-array'>;
}
declare module 'd3-array/index.js' {
  declare module.exports: $Exports<'d3-array'>;
}
declare module 'd3-array/src/array.js' {
  declare module.exports: $Exports<'d3-array/src/array'>;
}
declare module 'd3-array/src/ascending.js' {
  declare module.exports: $Exports<'d3-array/src/ascending'>;
}
declare module 'd3-array/src/bisect.js' {
  declare module.exports: $Exports<'d3-array/src/bisect'>;
}
declare module 'd3-array/src/bisector.js' {
  declare module.exports: $Exports<'d3-array/src/bisector'>;
}
declare module 'd3-array/src/constant.js' {
  declare module.exports: $Exports<'d3-array/src/constant'>;
}
declare module 'd3-array/src/cross.js' {
  declare module.exports: $Exports<'d3-array/src/cross'>;
}
declare module 'd3-array/src/descending.js' {
  declare module.exports: $Exports<'d3-array/src/descending'>;
}
declare module 'd3-array/src/deviation.js' {
  declare module.exports: $Exports<'d3-array/src/deviation'>;
}
declare module 'd3-array/src/extent.js' {
  declare module.exports: $Exports<'d3-array/src/extent'>;
}
declare module 'd3-array/src/histogram.js' {
  declare module.exports: $Exports<'d3-array/src/histogram'>;
}
declare module 'd3-array/src/identity.js' {
  declare module.exports: $Exports<'d3-array/src/identity'>;
}
declare module 'd3-array/src/max.js' {
  declare module.exports: $Exports<'d3-array/src/max'>;
}
declare module 'd3-array/src/mean.js' {
  declare module.exports: $Exports<'d3-array/src/mean'>;
}
declare module 'd3-array/src/median.js' {
  declare module.exports: $Exports<'d3-array/src/median'>;
}
declare module 'd3-array/src/merge.js' {
  declare module.exports: $Exports<'d3-array/src/merge'>;
}
declare module 'd3-array/src/min.js' {
  declare module.exports: $Exports<'d3-array/src/min'>;
}
declare module 'd3-array/src/number.js' {
  declare module.exports: $Exports<'d3-array/src/number'>;
}
declare module 'd3-array/src/pairs.js' {
  declare module.exports: $Exports<'d3-array/src/pairs'>;
}
declare module 'd3-array/src/permute.js' {
  declare module.exports: $Exports<'d3-array/src/permute'>;
}
declare module 'd3-array/src/quantile.js' {
  declare module.exports: $Exports<'d3-array/src/quantile'>;
}
declare module 'd3-array/src/range.js' {
  declare module.exports: $Exports<'d3-array/src/range'>;
}
declare module 'd3-array/src/scan.js' {
  declare module.exports: $Exports<'d3-array/src/scan'>;
}
declare module 'd3-array/src/shuffle.js' {
  declare module.exports: $Exports<'d3-array/src/shuffle'>;
}
declare module 'd3-array/src/sum.js' {
  declare module.exports: $Exports<'d3-array/src/sum'>;
}
declare module 'd3-array/src/threshold/freedmanDiaconis.js' {
  declare module.exports: $Exports<'d3-array/src/threshold/freedmanDiaconis'>;
}
declare module 'd3-array/src/threshold/scott.js' {
  declare module.exports: $Exports<'d3-array/src/threshold/scott'>;
}
declare module 'd3-array/src/threshold/sturges.js' {
  declare module.exports: $Exports<'d3-array/src/threshold/sturges'>;
}
declare module 'd3-array/src/ticks.js' {
  declare module.exports: $Exports<'d3-array/src/ticks'>;
}
declare module 'd3-array/src/transpose.js' {
  declare module.exports: $Exports<'d3-array/src/transpose'>;
}
declare module 'd3-array/src/variance.js' {
  declare module.exports: $Exports<'d3-array/src/variance'>;
}
declare module 'd3-array/src/zip.js' {
  declare module.exports: $Exports<'d3-array/src/zip'>;
}
