// flow-typed signature: be735722bffb485a8cf54a7c7080821a
// flow-typed version: <<STUB>>/danger-plugin-no-console_v1.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-no-console'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-no-console' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger-plugin-no-console/dist/index' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/inherited-summary' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/inner-link' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/manual' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/patch-for-local' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/prettify/prettify' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/pretty-print' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/search_index' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/search' {
  declare module.exports: any;
}

declare module 'danger-plugin-no-console/docs/script/test-summary' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger-plugin-no-console/dist/index.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/dist/index'>;
}
declare module 'danger-plugin-no-console/docs/script/inherited-summary.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/inherited-summary'>;
}
declare module 'danger-plugin-no-console/docs/script/inner-link.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/inner-link'>;
}
declare module 'danger-plugin-no-console/docs/script/manual.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/manual'>;
}
declare module 'danger-plugin-no-console/docs/script/patch-for-local.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/patch-for-local'>;
}
declare module 'danger-plugin-no-console/docs/script/prettify/prettify.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/prettify/prettify'>;
}
declare module 'danger-plugin-no-console/docs/script/pretty-print.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/pretty-print'>;
}
declare module 'danger-plugin-no-console/docs/script/search_index.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/search_index'>;
}
declare module 'danger-plugin-no-console/docs/script/search.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/search'>;
}
declare module 'danger-plugin-no-console/docs/script/test-summary.js' {
  declare module.exports: $Exports<'danger-plugin-no-console/docs/script/test-summary'>;
}
