// flow-typed signature: 45f3a6b6919397f3ea67b75c1a9601bf
// flow-typed version: <<STUB>>/danger-plugin-flow_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger-plugin-flow/dist/index' {
  declare module.exports: any;
}

declare module 'danger-plugin-flow/dist/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger-plugin-flow/dist/index.js' {
  declare module.exports: $Exports<'danger-plugin-flow/dist/index'>;
}
declare module 'danger-plugin-flow/dist/index.test.js' {
  declare module.exports: $Exports<'danger-plugin-flow/dist/index.test'>;
}
