// flow-typed signature: 7b69917a67b22d12810ba89bc8ffdec2
// flow-typed version: <<STUB>>/danger-plugin-yarn_v^1.2.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'danger-plugin-yarn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'danger-plugin-yarn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'danger-plugin-yarn/dist/danger-mock' {
  declare module.exports: any;
}

declare module 'danger-plugin-yarn/dist/index' {
  declare module.exports: any;
}

declare module 'danger-plugin-yarn/dist/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'danger-plugin-yarn/dist/danger-mock.js' {
  declare module.exports: $Exports<'danger-plugin-yarn/dist/danger-mock'>;
}
declare module 'danger-plugin-yarn/dist/index.js' {
  declare module.exports: $Exports<'danger-plugin-yarn/dist/index'>;
}
declare module 'danger-plugin-yarn/dist/index.test.js' {
  declare module.exports: $Exports<'danger-plugin-yarn/dist/index.test'>;
}
