// flow-typed signature: 4193c068fe558edea2fe8b024db8448c
// flow-typed version: <<STUB>>/datadog-metrics_v0.8.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'datadog-metrics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'datadog-metrics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'datadog-metrics/lib/aggregators' {
  declare module.exports: any;
}

declare module 'datadog-metrics/lib/loggers' {
  declare module.exports: any;
}

declare module 'datadog-metrics/lib/metrics' {
  declare module.exports: any;
}

declare module 'datadog-metrics/lib/reporters' {
  declare module.exports: any;
}

// Filename aliases
declare module 'datadog-metrics/index' {
  declare module.exports: $Exports<'datadog-metrics'>;
}
declare module 'datadog-metrics/index.js' {
  declare module.exports: $Exports<'datadog-metrics'>;
}
declare module 'datadog-metrics/lib/aggregators.js' {
  declare module.exports: $Exports<'datadog-metrics/lib/aggregators'>;
}
declare module 'datadog-metrics/lib/loggers.js' {
  declare module.exports: $Exports<'datadog-metrics/lib/loggers'>;
}
declare module 'datadog-metrics/lib/metrics.js' {
  declare module.exports: $Exports<'datadog-metrics/lib/metrics'>;
}
declare module 'datadog-metrics/lib/reporters.js' {
  declare module.exports: $Exports<'datadog-metrics/lib/reporters'>;
}
