// flow-typed signature: 1b6bfd1d8094619e9134e61f63e92a0f
// flow-typed version: <<STUB>>/draft-js-image-plugin_v2.0.0-rc8/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-image-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-image-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-image-plugin/lib/Image/index' {
  declare module.exports: any;
}

declare module 'draft-js-image-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-image-plugin/lib/modifiers/addImage' {
  declare module.exports: any;
}

declare module 'draft-js-image-plugin/postcss.config' {
  declare module.exports: any;
}

declare module 'draft-js-image-plugin/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-image-plugin/lib/Image/index.js' {
  declare module.exports: $Exports<'draft-js-image-plugin/lib/Image/index'>;
}
declare module 'draft-js-image-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-image-plugin/lib/index'>;
}
declare module 'draft-js-image-plugin/lib/modifiers/addImage.js' {
  declare module.exports: $Exports<'draft-js-image-plugin/lib/modifiers/addImage'>;
}
declare module 'draft-js-image-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-image-plugin/postcss.config'>;
}
declare module 'draft-js-image-plugin/webpack.config.js' {
  declare module.exports: $Exports<'draft-js-image-plugin/webpack.config'>;
}
