// flow-typed signature: 62c300788f61ec7382ffcd7ba580e1e3
// flow-typed version: <<STUB>>/draft-js-export-markdown_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-export-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-export-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-export-markdown/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-export-markdown/lib/stateToMarkdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-export-markdown/lib/main.js' {
  declare module.exports: $Exports<'draft-js-export-markdown/lib/main'>;
}
declare module 'draft-js-export-markdown/lib/stateToMarkdown.js' {
  declare module.exports: $Exports<'draft-js-export-markdown/lib/stateToMarkdown'>;
}
