// flow-typed signature: 9a561a1fa760295a878190beb98cda0d
// flow-typed version: <<STUB>>/draft-js-embed-plugin_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-embed-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-embed-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-embed-plugin/lib/bundle-embedStyles' {
  declare module.exports: any;
}

declare module 'draft-js-embed-plugin/lib/embed/index' {
  declare module.exports: any;
}

declare module 'draft-js-embed-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-embed-plugin/lib/modifiers/addEmbed' {
  declare module.exports: any;
}

declare module 'draft-js-embed-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-embed-plugin/lib/bundle-embedStyles.js' {
  declare module.exports: $Exports<'draft-js-embed-plugin/lib/bundle-embedStyles'>;
}
declare module 'draft-js-embed-plugin/lib/embed/index.js' {
  declare module.exports: $Exports<'draft-js-embed-plugin/lib/embed/index'>;
}
declare module 'draft-js-embed-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-embed-plugin/lib/index'>;
}
declare module 'draft-js-embed-plugin/lib/modifiers/addEmbed.js' {
  declare module.exports: $Exports<'draft-js-embed-plugin/lib/modifiers/addEmbed'>;
}
declare module 'draft-js-embed-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-embed-plugin/postcss.config'>;
}
