// flow-typed signature: b19d6fb70255137c591e442ccd68ecb8
// flow-typed version: <<STUB>>/draft-js-prism-plugin_v0.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-prism-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-prism-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-prism-plugin/dist/index' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-stage-2_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/draft-js-prism_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/flow-typed/npm/rimraf_vx.x.x' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/src/index' {
  declare module.exports: any;
}

declare module 'draft-js-prism-plugin/src/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-prism-plugin/dist/index.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/dist/index'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/babel-preset-stage-2_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/babel-preset-stage-2_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/draft-js-prism_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/draft-js-prism_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/prettier_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/flow-typed/npm/rimraf_vx.x.x.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/flow-typed/npm/rimraf_vx.x.x'>;
}
declare module 'draft-js-prism-plugin/src/index.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/src/index'>;
}
declare module 'draft-js-prism-plugin/src/test/index.test.js' {
  declare module.exports: $Exports<'draft-js-prism-plugin/src/test/index.test'>;
}
