// flow-typed signature: 26a9245f6d98367e4a7e3f48e00baaf8
// flow-typed version: <<STUB>>/draft-js_v0.10.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js/dist/Draft' {
  declare module.exports: any;
}

declare module 'draft-js/dist/Draft.min' {
  declare module.exports: any;
}

declare module 'draft-js/lib/addEntityToContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/addEntityToEntityMap' {
  declare module.exports: any;
}

declare module 'draft-js/lib/adjustBlockDepthForContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/applyEntityToContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/lib/applyEntityToContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/AtomicBlockUtils' {
  declare module.exports: any;
}

declare module 'draft-js/lib/BlockMap' {
  declare module.exports: any;
}

declare module 'draft-js/lib/BlockMapBuilder' {
  declare module.exports: any;
}

declare module 'draft-js/lib/BlockTree' {
  declare module.exports: any;
}

declare module 'draft-js/lib/CharacterMetadata' {
  declare module.exports: any;
}

declare module 'draft-js/lib/ComposedEntityMutability' {
  declare module.exports: any;
}

declare module 'draft-js/lib/ComposedEntityType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/CompositeDraftDecorator' {
  declare module.exports: any;
}

declare module 'draft-js/lib/ContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/lib/ContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/ContentStateInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/lib/convertFromDraftStateToRaw' {
  declare module.exports: any;
}

declare module 'draft-js/lib/convertFromHTMLToContentBlocks' {
  declare module.exports: any;
}

declare module 'draft-js/lib/convertFromRawToDraftState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/createCharacterList' {
  declare module.exports: any;
}

declare module 'draft-js/lib/createEntityInContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/decodeEntityRanges' {
  declare module.exports: any;
}

declare module 'draft-js/lib/decodeInlineStyleRanges' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DefaultDraftBlockRenderMap' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DefaultDraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DOMDerivedSelection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/Draft' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftBlockRenderConfig' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftBlockRenderMap' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftBlockType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftDecorator' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftDecoratorType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftDragType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditor.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorBlock.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorCommand' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorCompositionHandler' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorContents.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorDragHandler' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorEditHandler' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorLeaf.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorModes' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorPlaceholder.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorProps' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEditorTextNode.react' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEntityInstance' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEntityMutability' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEntitySegments' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftEntityType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftFeatureFlags-core' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftFeatureFlags' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftHandleValue' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftInsertionType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftJsDebugLogging' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftModifier' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftOffsetKeyPath' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftPasteProcessor' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftRange' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftRemovableWord' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftRemovalDirection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftScrollPosition' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftStringKey' {
  declare module.exports: any;
}

declare module 'draft-js/lib/DraftTextAlignment' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnBeforeInput' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnBlur' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnCompositionStart' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnCopy' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnCut' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnDragOver' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnDragStart' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnFocus' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnInput' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnKeyDown' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnPaste' {
  declare module.exports: any;
}

declare module 'draft-js/lib/editOnSelect' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EditorBidiService' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EditorChangeType' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EditorState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EditorStateCreationConfig' {
  declare module.exports: any;
}

declare module 'draft-js/lib/encodeEntityRanges' {
  declare module.exports: any;
}

declare module 'draft-js/lib/encodeInlineStyleRanges' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EntityMap' {
  declare module.exports: any;
}

declare module 'draft-js/lib/EntityRange' {
  declare module.exports: any;
}

declare module 'draft-js/lib/expandRangeToStartOfLine' {
  declare module.exports: any;
}

declare module 'draft-js/lib/findAncestorOffsetKey' {
  declare module.exports: any;
}

declare module 'draft-js/lib/findRangesImmutable' {
  declare module.exports: any;
}

declare module 'draft-js/lib/generateRandomKey' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getCharacterRemovalRange' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getContentStateFragment' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getDefaultKeyBinding' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getDraftEditorSelection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getDraftEditorSelectionWithNodes' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getEntityKeyForSelection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getFragmentFromSelection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getRangeBoundingClientRect' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getRangeClientRects' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getRangesForDraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getSafeBodyFromHTML' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getSampleStateForTesting' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getSelectionOffsetKeyForNode' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getTextAfterNearestEntity' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getTextContentFromFiles' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getUpdatedSelectionState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/getVisibleSelectionRect' {
  declare module.exports: any;
}

declare module 'draft-js/lib/InlineStyleRange' {
  declare module.exports: any;
}

declare module 'draft-js/lib/insertFragmentIntoContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/insertIntoList' {
  declare module.exports: any;
}

declare module 'draft-js/lib/insertTextIntoContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/isEventHandled' {
  declare module.exports: any;
}

declare module 'draft-js/lib/isSelectionAtLeafStart' {
  declare module.exports: any;
}

declare module 'draft-js/lib/isSoftNewlineEvent' {
  declare module.exports: any;
}

declare module 'draft-js/lib/KeyBindingUtil' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandBackspaceToStartOfLine' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandBackspaceWord' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandDeleteWord' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandInsertNewline' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandMoveSelectionToEndOfBlock' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandMoveSelectionToStartOfBlock' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandPlainBackspace' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandPlainDelete' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandTransposeCharacters' {
  declare module.exports: any;
}

declare module 'draft-js/lib/keyCommandUndo' {
  declare module.exports: any;
}

declare module 'draft-js/lib/modifyBlockForContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/moveBlockInContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/moveSelectionBackward' {
  declare module.exports: any;
}

declare module 'draft-js/lib/moveSelectionForward' {
  declare module.exports: any;
}

declare module 'draft-js/lib/RawDraftContentBlock' {
  declare module.exports: any;
}

declare module 'draft-js/lib/RawDraftContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/RawDraftEntity' {
  declare module.exports: any;
}

declare module 'draft-js/lib/removeEntitiesAtEdges' {
  declare module.exports: any;
}

declare module 'draft-js/lib/removeRangeFromContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/removeTextWithStrategy' {
  declare module.exports: any;
}

declare module 'draft-js/lib/RichTextEditorUtil' {
  declare module.exports: any;
}

declare module 'draft-js/lib/SampleDraftInlineStyle' {
  declare module.exports: any;
}

declare module 'draft-js/lib/sanitizeDraftText' {
  declare module.exports: any;
}

declare module 'draft-js/lib/SecondaryClipboard' {
  declare module.exports: any;
}

declare module 'draft-js/lib/SelectionState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/setDraftEditorSelection' {
  declare module.exports: any;
}

declare module 'draft-js/lib/splitBlockInContentState' {
  declare module.exports: any;
}

declare module 'draft-js/lib/splitTextIntoTextBlocks' {
  declare module.exports: any;
}

declare module 'draft-js/lib/updateEntityDataInContentState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js/dist/Draft.js' {
  declare module.exports: $Exports<'draft-js/dist/Draft'>;
}
declare module 'draft-js/dist/Draft.min.js' {
  declare module.exports: $Exports<'draft-js/dist/Draft.min'>;
}
declare module 'draft-js/lib/addEntityToContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/addEntityToContentState'>;
}
declare module 'draft-js/lib/addEntityToEntityMap.js' {
  declare module.exports: $Exports<'draft-js/lib/addEntityToEntityMap'>;
}
declare module 'draft-js/lib/adjustBlockDepthForContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/adjustBlockDepthForContentState'>;
}
declare module 'draft-js/lib/applyEntityToContentBlock.js' {
  declare module.exports: $Exports<'draft-js/lib/applyEntityToContentBlock'>;
}
declare module 'draft-js/lib/applyEntityToContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/applyEntityToContentState'>;
}
declare module 'draft-js/lib/AtomicBlockUtils.js' {
  declare module.exports: $Exports<'draft-js/lib/AtomicBlockUtils'>;
}
declare module 'draft-js/lib/BlockMap.js' {
  declare module.exports: $Exports<'draft-js/lib/BlockMap'>;
}
declare module 'draft-js/lib/BlockMapBuilder.js' {
  declare module.exports: $Exports<'draft-js/lib/BlockMapBuilder'>;
}
declare module 'draft-js/lib/BlockTree.js' {
  declare module.exports: $Exports<'draft-js/lib/BlockTree'>;
}
declare module 'draft-js/lib/CharacterMetadata.js' {
  declare module.exports: $Exports<'draft-js/lib/CharacterMetadata'>;
}
declare module 'draft-js/lib/ComposedEntityMutability.js' {
  declare module.exports: $Exports<'draft-js/lib/ComposedEntityMutability'>;
}
declare module 'draft-js/lib/ComposedEntityType.js' {
  declare module.exports: $Exports<'draft-js/lib/ComposedEntityType'>;
}
declare module 'draft-js/lib/CompositeDraftDecorator.js' {
  declare module.exports: $Exports<'draft-js/lib/CompositeDraftDecorator'>;
}
declare module 'draft-js/lib/ContentBlock.js' {
  declare module.exports: $Exports<'draft-js/lib/ContentBlock'>;
}
declare module 'draft-js/lib/ContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/ContentState'>;
}
declare module 'draft-js/lib/ContentStateInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/lib/ContentStateInlineStyle'>;
}
declare module 'draft-js/lib/convertFromDraftStateToRaw.js' {
  declare module.exports: $Exports<'draft-js/lib/convertFromDraftStateToRaw'>;
}
declare module 'draft-js/lib/convertFromHTMLToContentBlocks.js' {
  declare module.exports: $Exports<'draft-js/lib/convertFromHTMLToContentBlocks'>;
}
declare module 'draft-js/lib/convertFromRawToDraftState.js' {
  declare module.exports: $Exports<'draft-js/lib/convertFromRawToDraftState'>;
}
declare module 'draft-js/lib/createCharacterList.js' {
  declare module.exports: $Exports<'draft-js/lib/createCharacterList'>;
}
declare module 'draft-js/lib/createEntityInContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/createEntityInContentState'>;
}
declare module 'draft-js/lib/decodeEntityRanges.js' {
  declare module.exports: $Exports<'draft-js/lib/decodeEntityRanges'>;
}
declare module 'draft-js/lib/decodeInlineStyleRanges.js' {
  declare module.exports: $Exports<'draft-js/lib/decodeInlineStyleRanges'>;
}
declare module 'draft-js/lib/DefaultDraftBlockRenderMap.js' {
  declare module.exports: $Exports<'draft-js/lib/DefaultDraftBlockRenderMap'>;
}
declare module 'draft-js/lib/DefaultDraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/lib/DefaultDraftInlineStyle'>;
}
declare module 'draft-js/lib/DOMDerivedSelection.js' {
  declare module.exports: $Exports<'draft-js/lib/DOMDerivedSelection'>;
}
declare module 'draft-js/lib/Draft.js' {
  declare module.exports: $Exports<'draft-js/lib/Draft'>;
}
declare module 'draft-js/lib/DraftBlockRenderConfig.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftBlockRenderConfig'>;
}
declare module 'draft-js/lib/DraftBlockRenderMap.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftBlockRenderMap'>;
}
declare module 'draft-js/lib/DraftBlockType.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftBlockType'>;
}
declare module 'draft-js/lib/DraftDecorator.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftDecorator'>;
}
declare module 'draft-js/lib/DraftDecoratorType.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftDecoratorType'>;
}
declare module 'draft-js/lib/DraftDragType.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftDragType'>;
}
declare module 'draft-js/lib/DraftEditor.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditor.react'>;
}
declare module 'draft-js/lib/DraftEditorBlock.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorBlock.react'>;
}
declare module 'draft-js/lib/DraftEditorCommand.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorCommand'>;
}
declare module 'draft-js/lib/DraftEditorCompositionHandler.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorCompositionHandler'>;
}
declare module 'draft-js/lib/DraftEditorContents.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorContents.react'>;
}
declare module 'draft-js/lib/DraftEditorDragHandler.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorDragHandler'>;
}
declare module 'draft-js/lib/DraftEditorEditHandler.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorEditHandler'>;
}
declare module 'draft-js/lib/DraftEditorLeaf.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorLeaf.react'>;
}
declare module 'draft-js/lib/DraftEditorModes.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorModes'>;
}
declare module 'draft-js/lib/DraftEditorPlaceholder.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorPlaceholder.react'>;
}
declare module 'draft-js/lib/DraftEditorProps.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorProps'>;
}
declare module 'draft-js/lib/DraftEditorTextNode.react.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEditorTextNode.react'>;
}
declare module 'draft-js/lib/DraftEntity.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEntity'>;
}
declare module 'draft-js/lib/DraftEntityInstance.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEntityInstance'>;
}
declare module 'draft-js/lib/DraftEntityMutability.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEntityMutability'>;
}
declare module 'draft-js/lib/DraftEntitySegments.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEntitySegments'>;
}
declare module 'draft-js/lib/DraftEntityType.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftEntityType'>;
}
declare module 'draft-js/lib/DraftFeatureFlags-core.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftFeatureFlags-core'>;
}
declare module 'draft-js/lib/DraftFeatureFlags.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftFeatureFlags'>;
}
declare module 'draft-js/lib/DraftHandleValue.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftHandleValue'>;
}
declare module 'draft-js/lib/DraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftInlineStyle'>;
}
declare module 'draft-js/lib/DraftInsertionType.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftInsertionType'>;
}
declare module 'draft-js/lib/DraftJsDebugLogging.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftJsDebugLogging'>;
}
declare module 'draft-js/lib/DraftModifier.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftModifier'>;
}
declare module 'draft-js/lib/DraftOffsetKey.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftOffsetKey'>;
}
declare module 'draft-js/lib/DraftOffsetKeyPath.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftOffsetKeyPath'>;
}
declare module 'draft-js/lib/DraftPasteProcessor.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftPasteProcessor'>;
}
declare module 'draft-js/lib/DraftRange.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftRange'>;
}
declare module 'draft-js/lib/DraftRemovableWord.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftRemovableWord'>;
}
declare module 'draft-js/lib/DraftRemovalDirection.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftRemovalDirection'>;
}
declare module 'draft-js/lib/DraftScrollPosition.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftScrollPosition'>;
}
declare module 'draft-js/lib/DraftStringKey.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftStringKey'>;
}
declare module 'draft-js/lib/DraftTextAlignment.js' {
  declare module.exports: $Exports<'draft-js/lib/DraftTextAlignment'>;
}
declare module 'draft-js/lib/editOnBeforeInput.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnBeforeInput'>;
}
declare module 'draft-js/lib/editOnBlur.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnBlur'>;
}
declare module 'draft-js/lib/editOnCompositionStart.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnCompositionStart'>;
}
declare module 'draft-js/lib/editOnCopy.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnCopy'>;
}
declare module 'draft-js/lib/editOnCut.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnCut'>;
}
declare module 'draft-js/lib/editOnDragOver.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnDragOver'>;
}
declare module 'draft-js/lib/editOnDragStart.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnDragStart'>;
}
declare module 'draft-js/lib/editOnFocus.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnFocus'>;
}
declare module 'draft-js/lib/editOnInput.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnInput'>;
}
declare module 'draft-js/lib/editOnKeyDown.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnKeyDown'>;
}
declare module 'draft-js/lib/editOnPaste.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnPaste'>;
}
declare module 'draft-js/lib/editOnSelect.js' {
  declare module.exports: $Exports<'draft-js/lib/editOnSelect'>;
}
declare module 'draft-js/lib/EditorBidiService.js' {
  declare module.exports: $Exports<'draft-js/lib/EditorBidiService'>;
}
declare module 'draft-js/lib/EditorChangeType.js' {
  declare module.exports: $Exports<'draft-js/lib/EditorChangeType'>;
}
declare module 'draft-js/lib/EditorState.js' {
  declare module.exports: $Exports<'draft-js/lib/EditorState'>;
}
declare module 'draft-js/lib/EditorStateCreationConfig.js' {
  declare module.exports: $Exports<'draft-js/lib/EditorStateCreationConfig'>;
}
declare module 'draft-js/lib/encodeEntityRanges.js' {
  declare module.exports: $Exports<'draft-js/lib/encodeEntityRanges'>;
}
declare module 'draft-js/lib/encodeInlineStyleRanges.js' {
  declare module.exports: $Exports<'draft-js/lib/encodeInlineStyleRanges'>;
}
declare module 'draft-js/lib/EntityMap.js' {
  declare module.exports: $Exports<'draft-js/lib/EntityMap'>;
}
declare module 'draft-js/lib/EntityRange.js' {
  declare module.exports: $Exports<'draft-js/lib/EntityRange'>;
}
declare module 'draft-js/lib/expandRangeToStartOfLine.js' {
  declare module.exports: $Exports<'draft-js/lib/expandRangeToStartOfLine'>;
}
declare module 'draft-js/lib/findAncestorOffsetKey.js' {
  declare module.exports: $Exports<'draft-js/lib/findAncestorOffsetKey'>;
}
declare module 'draft-js/lib/findRangesImmutable.js' {
  declare module.exports: $Exports<'draft-js/lib/findRangesImmutable'>;
}
declare module 'draft-js/lib/generateRandomKey.js' {
  declare module.exports: $Exports<'draft-js/lib/generateRandomKey'>;
}
declare module 'draft-js/lib/getCharacterRemovalRange.js' {
  declare module.exports: $Exports<'draft-js/lib/getCharacterRemovalRange'>;
}
declare module 'draft-js/lib/getContentStateFragment.js' {
  declare module.exports: $Exports<'draft-js/lib/getContentStateFragment'>;
}
declare module 'draft-js/lib/getDefaultKeyBinding.js' {
  declare module.exports: $Exports<'draft-js/lib/getDefaultKeyBinding'>;
}
declare module 'draft-js/lib/getDraftEditorSelection.js' {
  declare module.exports: $Exports<'draft-js/lib/getDraftEditorSelection'>;
}
declare module 'draft-js/lib/getDraftEditorSelectionWithNodes.js' {
  declare module.exports: $Exports<'draft-js/lib/getDraftEditorSelectionWithNodes'>;
}
declare module 'draft-js/lib/getEntityKeyForSelection.js' {
  declare module.exports: $Exports<'draft-js/lib/getEntityKeyForSelection'>;
}
declare module 'draft-js/lib/getFragmentFromSelection.js' {
  declare module.exports: $Exports<'draft-js/lib/getFragmentFromSelection'>;
}
declare module 'draft-js/lib/getRangeBoundingClientRect.js' {
  declare module.exports: $Exports<'draft-js/lib/getRangeBoundingClientRect'>;
}
declare module 'draft-js/lib/getRangeClientRects.js' {
  declare module.exports: $Exports<'draft-js/lib/getRangeClientRects'>;
}
declare module 'draft-js/lib/getRangesForDraftEntity.js' {
  declare module.exports: $Exports<'draft-js/lib/getRangesForDraftEntity'>;
}
declare module 'draft-js/lib/getSafeBodyFromHTML.js' {
  declare module.exports: $Exports<'draft-js/lib/getSafeBodyFromHTML'>;
}
declare module 'draft-js/lib/getSampleStateForTesting.js' {
  declare module.exports: $Exports<'draft-js/lib/getSampleStateForTesting'>;
}
declare module 'draft-js/lib/getSelectionOffsetKeyForNode.js' {
  declare module.exports: $Exports<'draft-js/lib/getSelectionOffsetKeyForNode'>;
}
declare module 'draft-js/lib/getTextAfterNearestEntity.js' {
  declare module.exports: $Exports<'draft-js/lib/getTextAfterNearestEntity'>;
}
declare module 'draft-js/lib/getTextContentFromFiles.js' {
  declare module.exports: $Exports<'draft-js/lib/getTextContentFromFiles'>;
}
declare module 'draft-js/lib/getUpdatedSelectionState.js' {
  declare module.exports: $Exports<'draft-js/lib/getUpdatedSelectionState'>;
}
declare module 'draft-js/lib/getVisibleSelectionRect.js' {
  declare module.exports: $Exports<'draft-js/lib/getVisibleSelectionRect'>;
}
declare module 'draft-js/lib/InlineStyleRange.js' {
  declare module.exports: $Exports<'draft-js/lib/InlineStyleRange'>;
}
declare module 'draft-js/lib/insertFragmentIntoContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/insertFragmentIntoContentState'>;
}
declare module 'draft-js/lib/insertIntoList.js' {
  declare module.exports: $Exports<'draft-js/lib/insertIntoList'>;
}
declare module 'draft-js/lib/insertTextIntoContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/insertTextIntoContentState'>;
}
declare module 'draft-js/lib/isEventHandled.js' {
  declare module.exports: $Exports<'draft-js/lib/isEventHandled'>;
}
declare module 'draft-js/lib/isSelectionAtLeafStart.js' {
  declare module.exports: $Exports<'draft-js/lib/isSelectionAtLeafStart'>;
}
declare module 'draft-js/lib/isSoftNewlineEvent.js' {
  declare module.exports: $Exports<'draft-js/lib/isSoftNewlineEvent'>;
}
declare module 'draft-js/lib/KeyBindingUtil.js' {
  declare module.exports: $Exports<'draft-js/lib/KeyBindingUtil'>;
}
declare module 'draft-js/lib/keyCommandBackspaceToStartOfLine.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandBackspaceToStartOfLine'>;
}
declare module 'draft-js/lib/keyCommandBackspaceWord.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandBackspaceWord'>;
}
declare module 'draft-js/lib/keyCommandDeleteWord.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandDeleteWord'>;
}
declare module 'draft-js/lib/keyCommandInsertNewline.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandInsertNewline'>;
}
declare module 'draft-js/lib/keyCommandMoveSelectionToEndOfBlock.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandMoveSelectionToEndOfBlock'>;
}
declare module 'draft-js/lib/keyCommandMoveSelectionToStartOfBlock.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandMoveSelectionToStartOfBlock'>;
}
declare module 'draft-js/lib/keyCommandPlainBackspace.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandPlainBackspace'>;
}
declare module 'draft-js/lib/keyCommandPlainDelete.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandPlainDelete'>;
}
declare module 'draft-js/lib/keyCommandTransposeCharacters.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandTransposeCharacters'>;
}
declare module 'draft-js/lib/keyCommandUndo.js' {
  declare module.exports: $Exports<'draft-js/lib/keyCommandUndo'>;
}
declare module 'draft-js/lib/modifyBlockForContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/modifyBlockForContentState'>;
}
declare module 'draft-js/lib/moveBlockInContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/moveBlockInContentState'>;
}
declare module 'draft-js/lib/moveSelectionBackward.js' {
  declare module.exports: $Exports<'draft-js/lib/moveSelectionBackward'>;
}
declare module 'draft-js/lib/moveSelectionForward.js' {
  declare module.exports: $Exports<'draft-js/lib/moveSelectionForward'>;
}
declare module 'draft-js/lib/RawDraftContentBlock.js' {
  declare module.exports: $Exports<'draft-js/lib/RawDraftContentBlock'>;
}
declare module 'draft-js/lib/RawDraftContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/RawDraftContentState'>;
}
declare module 'draft-js/lib/RawDraftEntity.js' {
  declare module.exports: $Exports<'draft-js/lib/RawDraftEntity'>;
}
declare module 'draft-js/lib/removeEntitiesAtEdges.js' {
  declare module.exports: $Exports<'draft-js/lib/removeEntitiesAtEdges'>;
}
declare module 'draft-js/lib/removeRangeFromContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/removeRangeFromContentState'>;
}
declare module 'draft-js/lib/removeTextWithStrategy.js' {
  declare module.exports: $Exports<'draft-js/lib/removeTextWithStrategy'>;
}
declare module 'draft-js/lib/RichTextEditorUtil.js' {
  declare module.exports: $Exports<'draft-js/lib/RichTextEditorUtil'>;
}
declare module 'draft-js/lib/SampleDraftInlineStyle.js' {
  declare module.exports: $Exports<'draft-js/lib/SampleDraftInlineStyle'>;
}
declare module 'draft-js/lib/sanitizeDraftText.js' {
  declare module.exports: $Exports<'draft-js/lib/sanitizeDraftText'>;
}
declare module 'draft-js/lib/SecondaryClipboard.js' {
  declare module.exports: $Exports<'draft-js/lib/SecondaryClipboard'>;
}
declare module 'draft-js/lib/SelectionState.js' {
  declare module.exports: $Exports<'draft-js/lib/SelectionState'>;
}
declare module 'draft-js/lib/setDraftEditorSelection.js' {
  declare module.exports: $Exports<'draft-js/lib/setDraftEditorSelection'>;
}
declare module 'draft-js/lib/splitBlockInContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/splitBlockInContentState'>;
}
declare module 'draft-js/lib/splitTextIntoTextBlocks.js' {
  declare module.exports: $Exports<'draft-js/lib/splitTextIntoTextBlocks'>;
}
declare module 'draft-js/lib/updateEntityDataInContentState.js' {
  declare module.exports: $Exports<'draft-js/lib/updateEntityDataInContentState'>;
}
