// flow-typed signature: 09d7e9659de8df545ddd929e1792d7f0
// flow-typed version: <<STUB>>/draft-js-single-line-plugin_v^2.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-single-line-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-single-line-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-single-line-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-single-line-plugin/lib/utils' {
  declare module.exports: any;
}

declare module 'draft-js-single-line-plugin/test/fixtures/content' {
  declare module.exports: any;
}

declare module 'draft-js-single-line-plugin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-single-line-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-single-line-plugin/lib/index'>;
}
declare module 'draft-js-single-line-plugin/lib/utils.js' {
  declare module.exports: $Exports<'draft-js-single-line-plugin/lib/utils'>;
}
declare module 'draft-js-single-line-plugin/test/fixtures/content.js' {
  declare module.exports: $Exports<'draft-js-single-line-plugin/test/fixtures/content'>;
}
declare module 'draft-js-single-line-plugin/test/index.js' {
  declare module.exports: $Exports<'draft-js-single-line-plugin/test/index'>;
}
