// flow-typed signature: 389c153854ffcd0db04e39873c832a95
// flow-typed version: <<STUB>>/draft-js-import-markdown_v^1.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-import-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-import-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-import-markdown/lib/main' {
  declare module.exports: any;
}

declare module 'draft-js-import-markdown/lib/MarkdownParser' {
  declare module.exports: any;
}

declare module 'draft-js-import-markdown/lib/stateFromMarkdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-import-markdown/lib/main.js' {
  declare module.exports: $Exports<'draft-js-import-markdown/lib/main'>;
}
declare module 'draft-js-import-markdown/lib/MarkdownParser.js' {
  declare module.exports: $Exports<'draft-js-import-markdown/lib/MarkdownParser'>;
}
declare module 'draft-js-import-markdown/lib/stateFromMarkdown.js' {
  declare module.exports: $Exports<'draft-js-import-markdown/lib/stateFromMarkdown'>;
}
