// flow-typed signature: 80b6c75a3455344e47ed91d5c4a5970c
// flow-typed version: <<STUB>>/draftjs-to-markdown_v^0.4.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draftjs-to-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draftjs-to-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draftjs-to-markdown/lib/draftjs-to-markdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draftjs-to-markdown/lib/draftjs-to-markdown.js' {
  declare module.exports: $Exports<'draftjs-to-markdown/lib/draftjs-to-markdown'>;
}
