// flow-typed signature: 97eb122c8883bdc42dd8631a8ded5526
// flow-typed version: <<STUB>>/draft-js-linkify-plugin_v^2.0.0-beta1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'draft-js-linkify-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'draft-js-linkify-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'draft-js-linkify-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'draft-js-linkify-plugin/lib/Link/index' {
  declare module.exports: any;
}

declare module 'draft-js-linkify-plugin/lib/linkStrategy' {
  declare module.exports: any;
}

declare module 'draft-js-linkify-plugin/postcss.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'draft-js-linkify-plugin/lib/index.js' {
  declare module.exports: $Exports<'draft-js-linkify-plugin/lib/index'>;
}
declare module 'draft-js-linkify-plugin/lib/Link/index.js' {
  declare module.exports: $Exports<'draft-js-linkify-plugin/lib/Link/index'>;
}
declare module 'draft-js-linkify-plugin/lib/linkStrategy.js' {
  declare module.exports: $Exports<'draft-js-linkify-plugin/lib/linkStrategy'>;
}
declare module 'draft-js-linkify-plugin/postcss.config.js' {
  declare module.exports: $Exports<'draft-js-linkify-plugin/postcss.config'>;
}
