// flow-typed signature: 56cb87472f7011e6a22325af9a351724
// flow-typed version: <<STUB>>/electron-is-dev_v1.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-is-dev'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-is-dev' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'electron-is-dev/index' {
  declare module.exports: $Exports<'electron-is-dev'>;
}
declare module 'electron-is-dev/index.js' {
  declare module.exports: $Exports<'electron-is-dev'>;
}
