// flow-typed signature: 77130022186123cfc81d76787330354e
// flow-typed version: <<STUB>>/electron-window-state_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-window-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-window-state' {
  declare module.exports: any;
}
