// flow-typed signature: 8dcc1a3a7cbd786dc8b1f9b4b86f0051
// flow-typed version: <<STUB>>/emojis_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emojis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emojis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'emojis/index' {
  declare module.exports: $Exports<'emojis'>;
}
declare module 'emojis/index.js' {
  declare module.exports: $Exports<'emojis'>;
}
