// flow-typed signature: eebb83b37b65acefcb2a1285cdcd8f40
// flow-typed version: <<STUB>>/eslint-plugin-jest_v^21.6.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-jest/processors/__tests__/snapshot-processor.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/processors/snapshot-processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/no_focused_tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/no_identical_title.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/no_large_snapshots.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/no_skipped_tests.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/prefer_expect_assertions.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_be_null.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_be_undefined.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_have_length.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/__tests__/valid_expect.test' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no_disabled_tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no_focused_tests' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no_identical_title' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/no_large_snapshots' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer_expect_assertions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer_to_be_null' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer_to_be_undefined' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/prefer_to_have_length' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/util' {
  declare module.exports: any;
}

declare module 'eslint-plugin-jest/rules/valid_expect' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-jest/index' {
  declare module.exports: $Exports<'eslint-plugin-jest'>;
}
declare module 'eslint-plugin-jest/index.js' {
  declare module.exports: $Exports<'eslint-plugin-jest'>;
}
declare module 'eslint-plugin-jest/processors/__tests__/snapshot-processor.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/processors/__tests__/snapshot-processor.test'>;
}
declare module 'eslint-plugin-jest/processors/snapshot-processor.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/processors/snapshot-processor'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/no_focused_tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/no_focused_tests.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/no_identical_title.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/no_identical_title.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/no_large_snapshots.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/no_large_snapshots.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/no_skipped_tests.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/no_skipped_tests.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/prefer_expect_assertions.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/prefer_expect_assertions.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_be_null.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/prefer_to_be_null.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_be_undefined.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/prefer_to_be_undefined.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/prefer_to_have_length.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/prefer_to_have_length.test'>;
}
declare module 'eslint-plugin-jest/rules/__tests__/valid_expect.test.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/__tests__/valid_expect.test'>;
}
declare module 'eslint-plugin-jest/rules/no_disabled_tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no_disabled_tests'>;
}
declare module 'eslint-plugin-jest/rules/no_focused_tests.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no_focused_tests'>;
}
declare module 'eslint-plugin-jest/rules/no_identical_title.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no_identical_title'>;
}
declare module 'eslint-plugin-jest/rules/no_large_snapshots.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/no_large_snapshots'>;
}
declare module 'eslint-plugin-jest/rules/prefer_expect_assertions.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer_expect_assertions'>;
}
declare module 'eslint-plugin-jest/rules/prefer_to_be_null.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer_to_be_null'>;
}
declare module 'eslint-plugin-jest/rules/prefer_to_be_undefined.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer_to_be_undefined'>;
}
declare module 'eslint-plugin-jest/rules/prefer_to_have_length.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/prefer_to_have_length'>;
}
declare module 'eslint-plugin-jest/rules/util.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/util'>;
}
declare module 'eslint-plugin-jest/rules/valid_expect.js' {
  declare module.exports: $Exports<'eslint-plugin-jest/rules/valid_expect'>;
}
