// flow-typed signature: 0ab3677c8ee0ecd2c38c9d3b9a511bf2
// flow-typed version: <<STUB>>/expo_v25.0.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}
