// flow-typed signature: 3f270976cb128c991faff0ddfc6f6aa3
// flow-typed version: <<STUB>>/expo-server-sdk_v2.3.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-server-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-server-sdk' {
  declare module.exports: any;
}
