// flow-typed signature: 1cdaa5e3b96efaeacdd3cbc4b45b40d3
// flow-typed version: <<STUB>>/express-hot-shots_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-hot-shots'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-hot-shots' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-hot-shots/Gruntfile' {
  declare module.exports: any;
}

declare module 'express-hot-shots/lib/express-hot-shots' {
  declare module.exports: any;
}

declare module 'express-hot-shots/test/express-hot-shots' {
  declare module.exports: any;
}

declare module 'express-hot-shots/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-hot-shots/Gruntfile.js' {
  declare module.exports: $Exports<'express-hot-shots/Gruntfile'>;
}
declare module 'express-hot-shots/lib/express-hot-shots.js' {
  declare module.exports: $Exports<'express-hot-shots/lib/express-hot-shots'>;
}
declare module 'express-hot-shots/test/express-hot-shots.js' {
  declare module.exports: $Exports<'express-hot-shots/test/express-hot-shots'>;
}
declare module 'express-hot-shots/test/utils.js' {
  declare module.exports: $Exports<'express-hot-shots/test/utils'>;
}
