// flow-typed signature: d8aa1a3f1477f62d348c0919d3e44c4c
// flow-typed version: <<STUB>>/express-session_v^1.15.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-session/session/cookie' {
  declare module.exports: any;
}

declare module 'express-session/session/memory' {
  declare module.exports: any;
}

declare module 'express-session/session/session' {
  declare module.exports: any;
}

declare module 'express-session/session/store' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-session/index' {
  declare module.exports: $Exports<'express-session'>;
}
declare module 'express-session/index.js' {
  declare module.exports: $Exports<'express-session'>;
}
declare module 'express-session/session/cookie.js' {
  declare module.exports: $Exports<'express-session/session/cookie'>;
}
declare module 'express-session/session/memory.js' {
  declare module.exports: $Exports<'express-session/session/memory'>;
}
declare module 'express-session/session/session.js' {
  declare module.exports: $Exports<'express-session/session/session'>;
}
declare module 'express-session/session/store.js' {
  declare module.exports: $Exports<'express-session/session/store'>;
}
