// flow-typed signature: 1cdaa5e3b96efaeacdd3cbc4b45b40d3
// flow-typed version: <<STUB>>/express-statsd_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-statsd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-statsd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-statsd/Gruntfile' {
  declare module.exports: any;
}

declare module 'express-statsd/lib/express-statsd' {
  declare module.exports: any;
}

declare module 'express-statsd/test/express-statsd' {
  declare module.exports: any;
}

declare module 'express-statsd/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-statsd/Gruntfile.js' {
  declare module.exports: $Exports<'express-statsd/Gruntfile'>;
}
declare module 'express-statsd/lib/express-statsd.js' {
  declare module.exports: $Exports<'express-statsd/lib/express-statsd'>;
}
declare module 'express-statsd/test/express-statsd.js' {
  declare module.exports: $Exports<'express-statsd/test/express-statsd'>;
}
declare module 'express-statsd/test/utils.js' {
  declare module.exports: $Exports<'express-statsd/test/utils'>;
}
