// flow-typed signature: 50e4a9a233649fb4233e62784e3edca5
// flow-typed version: <<STUB>>/find-with-regex_v1.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'find-with-regex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'find-with-regex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'find-with-regex/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'find-with-regex/lib/index.js' {
  declare module.exports: $Exports<'find-with-regex/lib/index'>;
}
