// flow-typed signature: 8081a49937d21beca3490c3784696e2e
// flow-typed version: <<STUB>>/generic-pool_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'generic-pool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'generic-pool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'generic-pool/lib/DefaultEvictor' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/Deferred' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/Deque' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/DequeIterator' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/DoublyLinkedList' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/DoublyLinkedListIterator' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/errors' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/factoryValidator' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/Pool' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/PoolDefaults' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/PooledResource' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/PooledResourceStateEnum' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/PoolOptions' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/PriorityQueue' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/Queue' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/ResourceLoan' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/ResourceRequest' {
  declare module.exports: any;
}

declare module 'generic-pool/lib/utils' {
  declare module.exports: any;
}

declare module 'generic-pool/test/doubly-linked-list-iterator-test' {
  declare module.exports: any;
}

declare module 'generic-pool/test/doubly-linked-list-test' {
  declare module.exports: any;
}

declare module 'generic-pool/test/generic-pool-acquiretimeout-test' {
  declare module.exports: any;
}

declare module 'generic-pool/test/generic-pool-test' {
  declare module.exports: any;
}

declare module 'generic-pool/test/resource-request-test' {
  declare module.exports: any;
}

declare module 'generic-pool/test/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'generic-pool/index' {
  declare module.exports: $Exports<'generic-pool'>;
}
declare module 'generic-pool/index.js' {
  declare module.exports: $Exports<'generic-pool'>;
}
declare module 'generic-pool/lib/DefaultEvictor.js' {
  declare module.exports: $Exports<'generic-pool/lib/DefaultEvictor'>;
}
declare module 'generic-pool/lib/Deferred.js' {
  declare module.exports: $Exports<'generic-pool/lib/Deferred'>;
}
declare module 'generic-pool/lib/Deque.js' {
  declare module.exports: $Exports<'generic-pool/lib/Deque'>;
}
declare module 'generic-pool/lib/DequeIterator.js' {
  declare module.exports: $Exports<'generic-pool/lib/DequeIterator'>;
}
declare module 'generic-pool/lib/DoublyLinkedList.js' {
  declare module.exports: $Exports<'generic-pool/lib/DoublyLinkedList'>;
}
declare module 'generic-pool/lib/DoublyLinkedListIterator.js' {
  declare module.exports: $Exports<'generic-pool/lib/DoublyLinkedListIterator'>;
}
declare module 'generic-pool/lib/errors.js' {
  declare module.exports: $Exports<'generic-pool/lib/errors'>;
}
declare module 'generic-pool/lib/factoryValidator.js' {
  declare module.exports: $Exports<'generic-pool/lib/factoryValidator'>;
}
declare module 'generic-pool/lib/Pool.js' {
  declare module.exports: $Exports<'generic-pool/lib/Pool'>;
}
declare module 'generic-pool/lib/PoolDefaults.js' {
  declare module.exports: $Exports<'generic-pool/lib/PoolDefaults'>;
}
declare module 'generic-pool/lib/PooledResource.js' {
  declare module.exports: $Exports<'generic-pool/lib/PooledResource'>;
}
declare module 'generic-pool/lib/PooledResourceStateEnum.js' {
  declare module.exports: $Exports<'generic-pool/lib/PooledResourceStateEnum'>;
}
declare module 'generic-pool/lib/PoolOptions.js' {
  declare module.exports: $Exports<'generic-pool/lib/PoolOptions'>;
}
declare module 'generic-pool/lib/PriorityQueue.js' {
  declare module.exports: $Exports<'generic-pool/lib/PriorityQueue'>;
}
declare module 'generic-pool/lib/Queue.js' {
  declare module.exports: $Exports<'generic-pool/lib/Queue'>;
}
declare module 'generic-pool/lib/ResourceLoan.js' {
  declare module.exports: $Exports<'generic-pool/lib/ResourceLoan'>;
}
declare module 'generic-pool/lib/ResourceRequest.js' {
  declare module.exports: $Exports<'generic-pool/lib/ResourceRequest'>;
}
declare module 'generic-pool/lib/utils.js' {
  declare module.exports: $Exports<'generic-pool/lib/utils'>;
}
declare module 'generic-pool/test/doubly-linked-list-iterator-test.js' {
  declare module.exports: $Exports<'generic-pool/test/doubly-linked-list-iterator-test'>;
}
declare module 'generic-pool/test/doubly-linked-list-test.js' {
  declare module.exports: $Exports<'generic-pool/test/doubly-linked-list-test'>;
}
declare module 'generic-pool/test/generic-pool-acquiretimeout-test.js' {
  declare module.exports: $Exports<'generic-pool/test/generic-pool-acquiretimeout-test'>;
}
declare module 'generic-pool/test/generic-pool-test.js' {
  declare module.exports: $Exports<'generic-pool/test/generic-pool-test'>;
}
declare module 'generic-pool/test/resource-request-test.js' {
  declare module.exports: $Exports<'generic-pool/test/resource-request-test'>;
}
declare module 'generic-pool/test/utils.js' {
  declare module.exports: $Exports<'generic-pool/test/utils'>;
}
