// flow-typed signature: b0bb2a9576643b265ab3e8251bc10fea
// flow-typed version: <<STUB>>/graphql-crunch_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-crunch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-crunch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-crunch/src/crunch' {
  declare module.exports: any;
}

declare module 'graphql-crunch/src/index' {
  declare module.exports: any;
}

declare module 'graphql-crunch/src/uncrunch' {
  declare module.exports: any;
}

declare module 'graphql-crunch/src/utils' {
  declare module.exports: any;
}

declare module 'graphql-crunch/test/big' {
  declare module.exports: any;
}

declare module 'graphql-crunch/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-crunch/src/crunch.js' {
  declare module.exports: $Exports<'graphql-crunch/src/crunch'>;
}
declare module 'graphql-crunch/src/index.js' {
  declare module.exports: $Exports<'graphql-crunch/src/index'>;
}
declare module 'graphql-crunch/src/uncrunch.js' {
  declare module.exports: $Exports<'graphql-crunch/src/uncrunch'>;
}
declare module 'graphql-crunch/src/utils.js' {
  declare module.exports: $Exports<'graphql-crunch/src/utils'>;
}
declare module 'graphql-crunch/test/big.js' {
  declare module.exports: $Exports<'graphql-crunch/test/big'>;
}
declare module 'graphql-crunch/test/main.js' {
  declare module.exports: $Exports<'graphql-crunch/test/main'>;
}
