// flow-typed signature: 1c72c3b4cfd91eb48e0ad98292d2747f
// flow-typed version: <<STUB>>/graphql-date_v^1.0.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-date' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-date/test/graphql-date.test' {
  declare module.exports: any;
}

declare module 'graphql-date/test/legacy.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-date/index' {
  declare module.exports: $Exports<'graphql-date'>;
}
declare module 'graphql-date/index.js' {
  declare module.exports: $Exports<'graphql-date'>;
}
declare module 'graphql-date/test/graphql-date.test.js' {
  declare module.exports: $Exports<'graphql-date/test/graphql-date.test'>;
}
declare module 'graphql-date/test/legacy.test.js' {
  declare module.exports: $Exports<'graphql-date/test/legacy.test'>;
}
