// flow-typed signature: 5c212600a16cd77c524a6fdb88265c97
// flow-typed version: <<STUB>>/graphql-depth-limit_v1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-depth-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-depth-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'graphql-depth-limit/index' {
  declare module.exports: $Exports<'graphql-depth-limit'>;
}
declare module 'graphql-depth-limit/index.js' {
  declare module.exports: $Exports<'graphql-depth-limit'>;
}
