// flow-typed signature: c7ffbf4289373478465263cbf3b0dd67
// flow-typed version: <<STUB>>/graphql-tools_v^0.11.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tools'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tools' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tools/dist/autopublish' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Interfaces' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/Logger' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/mock' {
  declare module.exports: any;
}

declare module 'graphql-tools/dist/schemaGenerator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tools/dist/autopublish.js' {
  declare module.exports: $Exports<'graphql-tools/dist/autopublish'>;
}
declare module 'graphql-tools/dist/index.js' {
  declare module.exports: $Exports<'graphql-tools/dist/index'>;
}
declare module 'graphql-tools/dist/Interfaces.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Interfaces'>;
}
declare module 'graphql-tools/dist/Logger.js' {
  declare module.exports: $Exports<'graphql-tools/dist/Logger'>;
}
declare module 'graphql-tools/dist/mock.js' {
  declare module.exports: $Exports<'graphql-tools/dist/mock'>;
}
declare module 'graphql-tools/dist/schemaGenerator.js' {
  declare module.exports: $Exports<'graphql-tools/dist/schemaGenerator'>;
}
