// flow-typed signature: 7e13fef330f0277b8bcebda2776ef3ca
// flow-typed version: <<STUB>>/honeycomb-nodejs-magic_v1.0.0-beta1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'honeycomb-nodejs-magic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'honeycomb-nodejs-magic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'honeycomb-nodejs-magic/lib/async_tracker' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/async_tracker.test' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/event' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/index' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/index.test' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/bluebird-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/child_process-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/express-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/http-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/https-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/mpromise-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/mysql2-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/react-dom-server-magic' {
  declare module.exports: any;
}

declare module 'honeycomb-nodejs-magic/lib/magic/sequelize-magic' {
  declare module.exports: any;
}

// Filename aliases
declare module 'honeycomb-nodejs-magic/lib/async_tracker.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/async_tracker'>;
}
declare module 'honeycomb-nodejs-magic/lib/async_tracker.test.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/async_tracker.test'>;
}
declare module 'honeycomb-nodejs-magic/lib/event.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/event'>;
}
declare module 'honeycomb-nodejs-magic/lib/index.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/index'>;
}
declare module 'honeycomb-nodejs-magic/lib/index.test.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/index.test'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/bluebird-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/bluebird-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/child_process-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/child_process-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/express-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/express-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/http-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/http-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/https-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/https-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/mpromise-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/mpromise-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/mysql2-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/mysql2-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/react-dom-server-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/react-dom-server-magic'>;
}
declare module 'honeycomb-nodejs-magic/lib/magic/sequelize-magic.js' {
  declare module.exports: $Exports<'honeycomb-nodejs-magic/lib/magic/sequelize-magic'>;
}
