// flow-typed signature: fc353630324340213e1109c7c5d291c2
// flow-typed version: <<STUB>>/host-validation_v1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'host-validation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'host-validation' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'host-validation/example' {
  declare module.exports: any;
}

declare module 'host-validation/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'host-validation/example.js' {
  declare module.exports: $Exports<'host-validation/example'>;
}
declare module 'host-validation/index' {
  declare module.exports: $Exports<'host-validation'>;
}
declare module 'host-validation/index.js' {
  declare module.exports: $Exports<'host-validation'>;
}
declare module 'host-validation/test.js' {
  declare module.exports: $Exports<'host-validation/test'>;
}
