// flow-typed signature: 6053e19d426e023eb75efc94b6a6467d
// flow-typed version: <<STUB>>/imgix-core-js_v^1.0.6/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imgix-core-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imgix-core-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imgix-core-js/assert_version' {
  declare module.exports: any;
}

declare module 'imgix-core-js/dist/imgix-core-js' {
  declare module.exports: any;
}

declare module 'imgix-core-js/dist/imgix-core-js.min' {
  declare module.exports: any;
}

declare module 'imgix-core-js/test/test-client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imgix-core-js/assert_version.js' {
  declare module.exports: $Exports<'imgix-core-js/assert_version'>;
}
declare module 'imgix-core-js/dist/imgix-core-js.js' {
  declare module.exports: $Exports<'imgix-core-js/dist/imgix-core-js'>;
}
declare module 'imgix-core-js/dist/imgix-core-js.min.js' {
  declare module.exports: $Exports<'imgix-core-js/dist/imgix-core-js.min'>;
}
declare module 'imgix-core-js/test/test-client.js' {
  declare module.exports: $Exports<'imgix-core-js/test/test-client'>;
}
