// flow-typed signature: dd839dddc088c685479cec804cc45744
// flow-typed version: <<STUB>>/ioredis_v3.1.4/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ioredis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ioredis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ioredis/lib/cluster/connection_pool' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/delay_queue' {
  declare module.exports: any;
}

declare module 'ioredis/lib/cluster/index' {
  declare module.exports: any;
}

declare module 'ioredis/lib/command' {
  declare module.exports: any;
}

declare module 'ioredis/lib/commander' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/connectors/sentinel_connector' {
  declare module.exports: any;
}

declare module 'ioredis/lib/pipeline' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/event_handler' {
  declare module.exports: any;
}

declare module 'ioredis/lib/redis/parser' {
  declare module.exports: any;
}

declare module 'ioredis/lib/reply_error' {
  declare module.exports: any;
}

declare module 'ioredis/lib/scan_stream' {
  declare module.exports: any;
}

declare module 'ioredis/lib/script' {
  declare module.exports: any;
}

declare module 'ioredis/lib/subscription_set' {
  declare module.exports: any;
}

declare module 'ioredis/lib/transaction' {
  declare module.exports: any;
}

declare module 'ioredis/lib/utils/index' {
  declare module.exports: any;
}

declare module 'ioredis/lib/utils/lodash' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ioredis/index' {
  declare module.exports: $Exports<'ioredis'>;
}
declare module 'ioredis/index.js' {
  declare module.exports: $Exports<'ioredis'>;
}
declare module 'ioredis/lib/cluster/connection_pool.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/connection_pool'>;
}
declare module 'ioredis/lib/cluster/delay_queue.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/delay_queue'>;
}
declare module 'ioredis/lib/cluster/index.js' {
  declare module.exports: $Exports<'ioredis/lib/cluster/index'>;
}
declare module 'ioredis/lib/command.js' {
  declare module.exports: $Exports<'ioredis/lib/command'>;
}
declare module 'ioredis/lib/commander.js' {
  declare module.exports: $Exports<'ioredis/lib/commander'>;
}
declare module 'ioredis/lib/connectors/connector.js' {
  declare module.exports: $Exports<'ioredis/lib/connectors/connector'>;
}
declare module 'ioredis/lib/connectors/sentinel_connector.js' {
  declare module.exports: $Exports<'ioredis/lib/connectors/sentinel_connector'>;
}
declare module 'ioredis/lib/pipeline.js' {
  declare module.exports: $Exports<'ioredis/lib/pipeline'>;
}
declare module 'ioredis/lib/redis.js' {
  declare module.exports: $Exports<'ioredis/lib/redis'>;
}
declare module 'ioredis/lib/redis/event_handler.js' {
  declare module.exports: $Exports<'ioredis/lib/redis/event_handler'>;
}
declare module 'ioredis/lib/redis/parser.js' {
  declare module.exports: $Exports<'ioredis/lib/redis/parser'>;
}
declare module 'ioredis/lib/reply_error.js' {
  declare module.exports: $Exports<'ioredis/lib/reply_error'>;
}
declare module 'ioredis/lib/scan_stream.js' {
  declare module.exports: $Exports<'ioredis/lib/scan_stream'>;
}
declare module 'ioredis/lib/script.js' {
  declare module.exports: $Exports<'ioredis/lib/script'>;
}
declare module 'ioredis/lib/subscription_set.js' {
  declare module.exports: $Exports<'ioredis/lib/subscription_set'>;
}
declare module 'ioredis/lib/transaction.js' {
  declare module.exports: $Exports<'ioredis/lib/transaction'>;
}
declare module 'ioredis/lib/utils/index.js' {
  declare module.exports: $Exports<'ioredis/lib/utils/index'>;
}
declare module 'ioredis/lib/utils/lodash.js' {
  declare module.exports: $Exports<'ioredis/lib/utils/lodash'>;
}
