// flow-typed signature: 9fa009c72365bb6aac18eebef2857f11
// flow-typed version: <<STUB>>/is-html_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-html/index' {
  declare module.exports: $Exports<'is-html'>;
}
declare module 'is-html/index.js' {
  declare module.exports: $Exports<'is-html'>;
}
