// flow-typed signature: 1bad344dc8156085c533246ff88652e1
// flow-typed version: <<STUB>>/iterall_v1.x/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'iterall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'iterall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'iterall/index' {
  declare module.exports: $Exports<'iterall'>;
}
declare module 'iterall/index.js' {
  declare module.exports: $Exports<'iterall'>;
}
