// flow-typed signature: 6bb459b7c579c9cdb27e1b2e6771b0af
// flow-typed version: <<STUB>>/json-stringify-pretty-compact_v^1.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-stringify-pretty-compact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-stringify-pretty-compact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'json-stringify-pretty-compact/index' {
  declare module.exports: $Exports<'json-stringify-pretty-compact'>;
}
declare module 'json-stringify-pretty-compact/index.js' {
  declare module.exports: $Exports<'json-stringify-pretty-compact'>;
}
