// flow-typed signature: 43d782f1119e4b4366b7e20d8ade28a1
// flow-typed version: <<STUB>>/localstorage-memory_v^1.0.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'localstorage-memory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'localstorage-memory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'localstorage-memory/bin/test-browser' {
  declare module.exports: any;
}

declare module 'localstorage-memory/lib/localstorage-memory' {
  declare module.exports: any;
}

declare module 'localstorage-memory/tests/node.setup' {
  declare module.exports: any;
}

declare module 'localstorage-memory/tests/test.localstorage-memory' {
  declare module.exports: any;
}

declare module 'localstorage-memory/tests/webrunner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'localstorage-memory/bin/test-browser.js' {
  declare module.exports: $Exports<'localstorage-memory/bin/test-browser'>;
}
declare module 'localstorage-memory/lib/localstorage-memory.js' {
  declare module.exports: $Exports<'localstorage-memory/lib/localstorage-memory'>;
}
declare module 'localstorage-memory/tests/node.setup.js' {
  declare module.exports: $Exports<'localstorage-memory/tests/node.setup'>;
}
declare module 'localstorage-memory/tests/test.localstorage-memory.js' {
  declare module.exports: $Exports<'localstorage-memory/tests/test.localstorage-memory'>;
}
declare module 'localstorage-memory/tests/webrunner.js' {
  declare module.exports: $Exports<'localstorage-memory/tests/webrunner'>;
}
