// flow-typed signature: 72b2dfcb381160ae074fc97df0df8724
// flow-typed version: <<STUB>>/markdown-draft-js_v0.6.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-draft-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-draft-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-draft-js/karma.conf' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/lib/draft-to-markdown' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/lib/index' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/lib/markdown-to-draft' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/src/draft-to-markdown' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/src/index' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/src/markdown-to-draft' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/test/draft-to-markdown.spec' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/test/idempotency.spec' {
  declare module.exports: any;
}

declare module 'markdown-draft-js/test/markdown-to-draft.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-draft-js/karma.conf.js' {
  declare module.exports: $Exports<'markdown-draft-js/karma.conf'>;
}
declare module 'markdown-draft-js/lib/draft-to-markdown.js' {
  declare module.exports: $Exports<'markdown-draft-js/lib/draft-to-markdown'>;
}
declare module 'markdown-draft-js/lib/index.js' {
  declare module.exports: $Exports<'markdown-draft-js/lib/index'>;
}
declare module 'markdown-draft-js/lib/markdown-to-draft.js' {
  declare module.exports: $Exports<'markdown-draft-js/lib/markdown-to-draft'>;
}
declare module 'markdown-draft-js/src/draft-to-markdown.js' {
  declare module.exports: $Exports<'markdown-draft-js/src/draft-to-markdown'>;
}
declare module 'markdown-draft-js/src/index.js' {
  declare module.exports: $Exports<'markdown-draft-js/src/index'>;
}
declare module 'markdown-draft-js/src/markdown-to-draft.js' {
  declare module.exports: $Exports<'markdown-draft-js/src/markdown-to-draft'>;
}
declare module 'markdown-draft-js/test/draft-to-markdown.spec.js' {
  declare module.exports: $Exports<'markdown-draft-js/test/draft-to-markdown.spec'>;
}
declare module 'markdown-draft-js/test/idempotency.spec.js' {
  declare module.exports: $Exports<'markdown-draft-js/test/idempotency.spec'>;
}
declare module 'markdown-draft-js/test/markdown-to-draft.spec.js' {
  declare module.exports: $Exports<'markdown-draft-js/test/markdown-to-draft.spec'>;
}
