// flow-typed signature: 6a0e98d916be7700aa90d4001fb377f3
// flow-typed version: <<STUB>>/micromatch_v^3.0.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'micromatch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'micromatch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'micromatch/lib/cache' {
  declare module.exports: any;
}

declare module 'micromatch/lib/compilers' {
  declare module.exports: any;
}

declare module 'micromatch/lib/parsers' {
  declare module.exports: any;
}

declare module 'micromatch/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'micromatch/index' {
  declare module.exports: $Exports<'micromatch'>;
}
declare module 'micromatch/index.js' {
  declare module.exports: $Exports<'micromatch'>;
}
declare module 'micromatch/lib/cache.js' {
  declare module.exports: $Exports<'micromatch/lib/cache'>;
}
declare module 'micromatch/lib/compilers.js' {
  declare module.exports: $Exports<'micromatch/lib/compilers'>;
}
declare module 'micromatch/lib/parsers.js' {
  declare module.exports: $Exports<'micromatch/lib/parsers'>;
}
declare module 'micromatch/lib/utils.js' {
  declare module.exports: $Exports<'micromatch/lib/utils'>;
}
