// flow-typed signature: 26d26f346507b3fc6d8a89a78b3fb30a
// flow-typed version: <<STUB>>/node-env-file_v^0.1.8/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-env-file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-env-file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-env-file/examples/basic' {
  declare module.exports: any;
}

declare module 'node-env-file/lib/index' {
  declare module.exports: any;
}

declare module 'node-env-file/test/helper' {
  declare module.exports: any;
}

declare module 'node-env-file/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-env-file/examples/basic.js' {
  declare module.exports: $Exports<'node-env-file/examples/basic'>;
}
declare module 'node-env-file/index' {
  declare module.exports: $Exports<'node-env-file'>;
}
declare module 'node-env-file/index.js' {
  declare module.exports: $Exports<'node-env-file'>;
}
declare module 'node-env-file/lib/index.js' {
  declare module.exports: $Exports<'node-env-file/lib/index'>;
}
declare module 'node-env-file/test/helper.js' {
  declare module.exports: $Exports<'node-env-file/test/helper'>;
}
declare module 'node-env-file/test/index.js' {
  declare module.exports: $Exports<'node-env-file/test/index'>;
}
