// flow-typed signature: d5245c9e405c61c1286f26f51dfed66f
// flow-typed version: <<STUB>>/now-env_v^3.0.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'now-env'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'now-env' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'now-env/lib/apply-env' {
  declare module.exports: any;
}

declare module 'now-env/lib/get-value' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-now-json' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-pkg-json' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-required' {
  declare module.exports: any;
}

declare module 'now-env/lib/load-secrets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'now-env/index' {
  declare module.exports: $Exports<'now-env'>;
}
declare module 'now-env/index.js' {
  declare module.exports: $Exports<'now-env'>;
}
declare module 'now-env/lib/apply-env.js' {
  declare module.exports: $Exports<'now-env/lib/apply-env'>;
}
declare module 'now-env/lib/get-value.js' {
  declare module.exports: $Exports<'now-env/lib/get-value'>;
}
declare module 'now-env/lib/load-now-json.js' {
  declare module.exports: $Exports<'now-env/lib/load-now-json'>;
}
declare module 'now-env/lib/load-pkg-json.js' {
  declare module.exports: $Exports<'now-env/lib/load-pkg-json'>;
}
declare module 'now-env/lib/load-required.js' {
  declare module.exports: $Exports<'now-env/lib/load-required'>;
}
declare module 'now-env/lib/load-secrets.js' {
  declare module.exports: $Exports<'now-env/lib/load-secrets'>;
}
