// flow-typed signature: 7c8ae3a34314f01d724bea074dd898ae
// flow-typed version: <<STUB>>/optics-agent_v^1.1.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'optics-agent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'optics-agent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'optics-agent/dist/Agent' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/DefaultAgent' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/index' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/Instrument' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/Normalize' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/normalizedPrinter' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/Proto' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/Report' {
  declare module.exports: any;
}

declare module 'optics-agent/dist/separateOperations' {
  declare module.exports: any;
}

// Filename aliases
declare module 'optics-agent/dist/Agent.js' {
  declare module.exports: $Exports<'optics-agent/dist/Agent'>;
}
declare module 'optics-agent/dist/DefaultAgent.js' {
  declare module.exports: $Exports<'optics-agent/dist/DefaultAgent'>;
}
declare module 'optics-agent/dist/index.js' {
  declare module.exports: $Exports<'optics-agent/dist/index'>;
}
declare module 'optics-agent/dist/Instrument.js' {
  declare module.exports: $Exports<'optics-agent/dist/Instrument'>;
}
declare module 'optics-agent/dist/Normalize.js' {
  declare module.exports: $Exports<'optics-agent/dist/Normalize'>;
}
declare module 'optics-agent/dist/normalizedPrinter.js' {
  declare module.exports: $Exports<'optics-agent/dist/normalizedPrinter'>;
}
declare module 'optics-agent/dist/Proto.js' {
  declare module.exports: $Exports<'optics-agent/dist/Proto'>;
}
declare module 'optics-agent/dist/Report.js' {
  declare module.exports: $Exports<'optics-agent/dist/Report'>;
}
declare module 'optics-agent/dist/separateOperations.js' {
  declare module.exports: $Exports<'optics-agent/dist/separateOperations'>;
}
