// flow-typed signature: bb32213050c47d2fba9e8852de4040eb
// flow-typed version: <<STUB>>/passport-twitter_v^1.0.4/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-twitter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-twitter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-twitter/lib/errors/apierror' {
  declare module.exports: any;
}

declare module 'passport-twitter/lib/index' {
  declare module.exports: any;
}

declare module 'passport-twitter/lib/profile' {
  declare module.exports: any;
}

declare module 'passport-twitter/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-twitter/lib/errors/apierror.js' {
  declare module.exports: $Exports<'passport-twitter/lib/errors/apierror'>;
}
declare module 'passport-twitter/lib/index.js' {
  declare module.exports: $Exports<'passport-twitter/lib/index'>;
}
declare module 'passport-twitter/lib/profile.js' {
  declare module.exports: $Exports<'passport-twitter/lib/profile'>;
}
declare module 'passport-twitter/lib/strategy.js' {
  declare module.exports: $Exports<'passport-twitter/lib/strategy'>;
}
