// flow-typed signature: f9045e098bc233689452b66cabf99bf2
// flow-typed version: <<STUB>>/passport-github2_v^0.1.10/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-github2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-github2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-github2/lib/index' {
  declare module.exports: any;
}

declare module 'passport-github2/lib/profile' {
  declare module.exports: any;
}

declare module 'passport-github2/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-github2/lib/index.js' {
  declare module.exports: $Exports<'passport-github2/lib/index'>;
}
declare module 'passport-github2/lib/profile.js' {
  declare module.exports: $Exports<'passport-github2/lib/profile'>;
}
declare module 'passport-github2/lib/strategy.js' {
  declare module.exports: $Exports<'passport-github2/lib/strategy'>;
}
