// flow-typed signature: 90325d4fc34bbec0d4643204d570d555
// flow-typed version: <<STUB>>/postmark_v^1.4.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postmark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postmark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postmark/docs/scripts/bootstrap-dropdown' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/bootstrap-tab' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/docstrap.lib' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/prettify/jquery.min' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/prettify/lang-css' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/prettify/prettify' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/sunlight' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/toc' {
  declare module.exports: any;
}

declare module 'postmark/docs/scripts/URI' {
  declare module.exports: any;
}

declare module 'postmark/lib/postmark/AdminClient' {
  declare module.exports: any;
}

declare module 'postmark/lib/postmark/Client' {
  declare module.exports: any;
}

declare module 'postmark/lib/postmark/clientDefaults' {
  declare module.exports: any;
}

declare module 'postmark/lib/postmark/documentationTypeDefs' {
  declare module.exports: any;
}

declare module 'postmark/lib/postmark/index' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_adminClientDomainManagement' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_adminClientServerManagement' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_adminClientSignatureManagement' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientBounceProcessing' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientClickStatistics' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientMessageProcessing' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientMessageStatistics' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientOpenHandling' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientServerHandling' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientTemplateHandling' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_clientTriggerProcessing' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_generalClientTests' {
  declare module.exports: any;
}

declare module 'postmark/tests/fixture_postmarkClientSending' {
  declare module.exports: any;
}

declare module 'postmark/tests/test_helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postmark/docs/scripts/bootstrap-dropdown.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/bootstrap-dropdown'>;
}
declare module 'postmark/docs/scripts/bootstrap-tab.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/bootstrap-tab'>;
}
declare module 'postmark/docs/scripts/docstrap.lib.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/docstrap.lib'>;
}
declare module 'postmark/docs/scripts/prettify/jquery.min.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/prettify/jquery.min'>;
}
declare module 'postmark/docs/scripts/prettify/lang-css.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/prettify/lang-css'>;
}
declare module 'postmark/docs/scripts/prettify/prettify.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/prettify/prettify'>;
}
declare module 'postmark/docs/scripts/sunlight.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/sunlight'>;
}
declare module 'postmark/docs/scripts/toc.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/toc'>;
}
declare module 'postmark/docs/scripts/URI.js' {
  declare module.exports: $Exports<'postmark/docs/scripts/URI'>;
}
declare module 'postmark/lib/postmark/AdminClient.js' {
  declare module.exports: $Exports<'postmark/lib/postmark/AdminClient'>;
}
declare module 'postmark/lib/postmark/Client.js' {
  declare module.exports: $Exports<'postmark/lib/postmark/Client'>;
}
declare module 'postmark/lib/postmark/clientDefaults.js' {
  declare module.exports: $Exports<'postmark/lib/postmark/clientDefaults'>;
}
declare module 'postmark/lib/postmark/documentationTypeDefs.js' {
  declare module.exports: $Exports<'postmark/lib/postmark/documentationTypeDefs'>;
}
declare module 'postmark/lib/postmark/index.js' {
  declare module.exports: $Exports<'postmark/lib/postmark/index'>;
}
declare module 'postmark/tests/fixture_adminClientDomainManagement.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_adminClientDomainManagement'>;
}
declare module 'postmark/tests/fixture_adminClientServerManagement.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_adminClientServerManagement'>;
}
declare module 'postmark/tests/fixture_adminClientSignatureManagement.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_adminClientSignatureManagement'>;
}
declare module 'postmark/tests/fixture_clientBounceProcessing.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientBounceProcessing'>;
}
declare module 'postmark/tests/fixture_clientClickStatistics.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientClickStatistics'>;
}
declare module 'postmark/tests/fixture_clientMessageProcessing.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientMessageProcessing'>;
}
declare module 'postmark/tests/fixture_clientMessageStatistics.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientMessageStatistics'>;
}
declare module 'postmark/tests/fixture_clientOpenHandling.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientOpenHandling'>;
}
declare module 'postmark/tests/fixture_clientServerHandling.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientServerHandling'>;
}
declare module 'postmark/tests/fixture_clientTemplateHandling.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientTemplateHandling'>;
}
declare module 'postmark/tests/fixture_clientTriggerProcessing.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_clientTriggerProcessing'>;
}
declare module 'postmark/tests/fixture_generalClientTests.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_generalClientTests'>;
}
declare module 'postmark/tests/fixture_postmarkClientSending.js' {
  declare module.exports: $Exports<'postmark/tests/fixture_postmarkClientSending'>;
}
declare module 'postmark/tests/test_helpers.js' {
  declare module.exports: $Exports<'postmark/tests/test_helpers'>;
}
