// flow-typed signature: cc7908af5df1f45860afe31151da7dac
// flow-typed version: <<STUB>>/raven_v^2.0.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raven'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raven' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raven/lib/client' {
  declare module.exports: any;
}

declare module 'raven/lib/instrumentation/console' {
  declare module.exports: any;
}

declare module 'raven/lib/instrumentation/http' {
  declare module.exports: any;
}

declare module 'raven/lib/instrumentation/instrumentor' {
  declare module.exports: any;
}

declare module 'raven/lib/instrumentation/pg' {
  declare module.exports: any;
}

declare module 'raven/lib/parsers' {
  declare module.exports: any;
}

declare module 'raven/lib/transports' {
  declare module.exports: any;
}

declare module 'raven/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raven/index' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/index.js' {
  declare module.exports: $Exports<'raven'>;
}
declare module 'raven/lib/client.js' {
  declare module.exports: $Exports<'raven/lib/client'>;
}
declare module 'raven/lib/instrumentation/console.js' {
  declare module.exports: $Exports<'raven/lib/instrumentation/console'>;
}
declare module 'raven/lib/instrumentation/http.js' {
  declare module.exports: $Exports<'raven/lib/instrumentation/http'>;
}
declare module 'raven/lib/instrumentation/instrumentor.js' {
  declare module.exports: $Exports<'raven/lib/instrumentation/instrumentor'>;
}
declare module 'raven/lib/instrumentation/pg.js' {
  declare module.exports: $Exports<'raven/lib/instrumentation/pg'>;
}
declare module 'raven/lib/parsers.js' {
  declare module.exports: $Exports<'raven/lib/parsers'>;
}
declare module 'raven/lib/transports.js' {
  declare module.exports: $Exports<'raven/lib/transports'>;
}
declare module 'raven/lib/utils.js' {
  declare module.exports: $Exports<'raven/lib/utils'>;
}
