// flow-typed signature: dfcf03dc1a3f237551ec04c69d552049
// flow-typed version: <<STUB>>/react-visibility-sensor_v5.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-visibility-sensor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-visibility-sensor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-visibility-sensor/dist/visibility-sensor' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/dist/visibility-sensor.min' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/example-umd/main' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/example/main' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/gulpfile' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/karma.conf' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/lib/is-visible-with-offset' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/testconf' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/tests/bundle' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/tests/visibility-sensor-spec' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/visibility-sensor' {
  declare module.exports: any;
}

declare module 'react-visibility-sensor/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-visibility-sensor/dist/visibility-sensor.js' {
  declare module.exports: $Exports<'react-visibility-sensor/dist/visibility-sensor'>;
}
declare module 'react-visibility-sensor/dist/visibility-sensor.min.js' {
  declare module.exports: $Exports<'react-visibility-sensor/dist/visibility-sensor.min'>;
}
declare module 'react-visibility-sensor/example-umd/main.js' {
  declare module.exports: $Exports<'react-visibility-sensor/example-umd/main'>;
}
declare module 'react-visibility-sensor/example/dist/bundle.js' {
  declare module.exports: $Exports<'react-visibility-sensor/example/dist/bundle'>;
}
declare module 'react-visibility-sensor/example/main.js' {
  declare module.exports: $Exports<'react-visibility-sensor/example/main'>;
}
declare module 'react-visibility-sensor/gulpfile.js' {
  declare module.exports: $Exports<'react-visibility-sensor/gulpfile'>;
}
declare module 'react-visibility-sensor/karma.conf.js' {
  declare module.exports: $Exports<'react-visibility-sensor/karma.conf'>;
}
declare module 'react-visibility-sensor/lib/is-visible-with-offset.js' {
  declare module.exports: $Exports<'react-visibility-sensor/lib/is-visible-with-offset'>;
}
declare module 'react-visibility-sensor/testconf.js' {
  declare module.exports: $Exports<'react-visibility-sensor/testconf'>;
}
declare module 'react-visibility-sensor/tests/bundle.js' {
  declare module.exports: $Exports<'react-visibility-sensor/tests/bundle'>;
}
declare module 'react-visibility-sensor/tests/visibility-sensor-spec.jsx' {
  declare module.exports: $Exports<'react-visibility-sensor/tests/visibility-sensor-spec'>;
}
declare module 'react-visibility-sensor/visibility-sensor.js' {
  declare module.exports: $Exports<'react-visibility-sensor/visibility-sensor'>;
}
declare module 'react-visibility-sensor/webpack.config.js' {
  declare module.exports: $Exports<'react-visibility-sensor/webpack.config'>;
}
