// flow-typed signature: e4fabee0a29fd025cb9354e1b63344aa
// flow-typed version: <<STUB>>/react-hot-loader_v4.3.11/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-hot-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-hot-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-hot-loader/babel' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/babel.development' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/babel.production.min' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/react-hot-loader.development' {
  declare module.exports: any;
}

declare module 'react-hot-loader/dist/react-hot-loader.production.min' {
  declare module.exports: any;
}

declare module 'react-hot-loader/patch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-hot-loader/babel.js' {
  declare module.exports: $Exports<'react-hot-loader/babel'>;
}
declare module 'react-hot-loader/dist/babel.development.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/babel.development'>;
}
declare module 'react-hot-loader/dist/babel.production.min.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/babel.production.min'>;
}
declare module 'react-hot-loader/dist/react-hot-loader.development.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/react-hot-loader.development'>;
}
declare module 'react-hot-loader/dist/react-hot-loader.production.min.js' {
  declare module.exports: $Exports<'react-hot-loader/dist/react-hot-loader.production.min'>;
}
declare module 'react-hot-loader/index' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/index.js' {
  declare module.exports: $Exports<'react-hot-loader'>;
}
declare module 'react-hot-loader/patch.js' {
  declare module.exports: $Exports<'react-hot-loader/patch'>;
}
