// flow-typed signature: 3616931cff0dd9b73bbe98046f6a84d6
// flow-typed version: <<STUB>>/react-popper_v1.0.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-popper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-popper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-popper/dist/index.umd' {
  declare module.exports: any;
}

declare module 'react-popper/dist/index.umd.min' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/__typings__/main-test' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/index' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/Manager' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/Popper' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/Reference' {
  declare module.exports: any;
}

declare module 'react-popper/lib/cjs/utils' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/__typings__/main-test' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/index' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/Manager' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/Popper' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/Reference' {
  declare module.exports: any;
}

declare module 'react-popper/lib/esm/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-popper/dist/index.umd.js' {
  declare module.exports: $Exports<'react-popper/dist/index.umd'>;
}
declare module 'react-popper/dist/index.umd.min.js' {
  declare module.exports: $Exports<'react-popper/dist/index.umd.min'>;
}
declare module 'react-popper/lib/cjs/__typings__/main-test.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/__typings__/main-test'>;
}
declare module 'react-popper/lib/cjs/index.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/index'>;
}
declare module 'react-popper/lib/cjs/Manager.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/Manager'>;
}
declare module 'react-popper/lib/cjs/Popper.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/Popper'>;
}
declare module 'react-popper/lib/cjs/Reference.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/Reference'>;
}
declare module 'react-popper/lib/cjs/utils.js' {
  declare module.exports: $Exports<'react-popper/lib/cjs/utils'>;
}
declare module 'react-popper/lib/esm/__typings__/main-test.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/__typings__/main-test'>;
}
declare module 'react-popper/lib/esm/index.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/index'>;
}
declare module 'react-popper/lib/esm/Manager.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/Manager'>;
}
declare module 'react-popper/lib/esm/Popper.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/Popper'>;
}
declare module 'react-popper/lib/esm/Reference.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/Reference'>;
}
declare module 'react-popper/lib/esm/utils.js' {
  declare module.exports: $Exports<'react-popper/lib/esm/utils'>;
}
