// flow-typed signature: ec9430de7a06c401c6f2ed6c6e633c47
// flow-typed version: <<STUB>>/react-apollo_v1.2.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/browser' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/queryRecycler' {
  declare module.exports: any;
}

declare module 'react-apollo/QueryRecyclerProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.browser.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/server' {
  declare module.exports: any;
}

declare module 'react-apollo/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-apollo/test-utils' {
  declare module.exports: any;
}

declare module 'react-apollo/types' {
  declare module.exports: any;
}

declare module 'react-apollo/withApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/ApolloProvider'>;
}
declare module 'react-apollo/browser.js' {
  declare module.exports: $Exports<'react-apollo/browser'>;
}
declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/invariant_v2.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.pick_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/object-assign_v4.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux_vx.x.x'>;
}
declare module 'react-apollo/graphql.js' {
  declare module.exports: $Exports<'react-apollo/graphql'>;
}
declare module 'react-apollo/index' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/index.js' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/parser.js' {
  declare module.exports: $Exports<'react-apollo/parser'>;
}
declare module 'react-apollo/queryRecycler.js' {
  declare module.exports: $Exports<'react-apollo/queryRecycler'>;
}
declare module 'react-apollo/QueryRecyclerProvider.js' {
  declare module.exports: $Exports<'react-apollo/QueryRecyclerProvider'>;
}
declare module 'react-apollo/react-apollo.browser.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.browser.umd'>;
}
declare module 'react-apollo/react-apollo.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.umd'>;
}
declare module 'react-apollo/server.js' {
  declare module.exports: $Exports<'react-apollo/server'>;
}
declare module 'react-apollo/shallowEqual.js' {
  declare module.exports: $Exports<'react-apollo/shallowEqual'>;
}
declare module 'react-apollo/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/test-utils'>;
}
declare module 'react-apollo/types.js' {
  declare module.exports: $Exports<'react-apollo/types'>;
}
declare module 'react-apollo/withApollo.js' {
  declare module.exports: $Exports<'react-apollo/withApollo'>;
}
