// flow-typed signature: b0b91aec72b7c1c4b527bd6e30eb581f
// flow-typed version: <<STUB>>/react-loadable_v4.x/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-loadable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-loadable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-loadable/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-loadable/lib/index.js' {
  declare module.exports: $Exports<'react-loadable/lib/index'>;
}
