// flow-typed signature: de7f9efdac766d6a9c8131b0be38f278
// flow-typed version: <<STUB>>/react-native-picker-select_v3.1.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-picker-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-picker-select' {
  declare export type PickerItem = {
    label: string,
    value: string,
    key?: string,
    color?: string
  }

  declare export type PickerProps = {
    onValueChange: (value: string, index: number) => void,
    items: PickerItem[],
    value: ?string,
    placeholder?: {
      label: string,
      value: ?string
    },
    disabled?: bool,
    style?: Object,
    hideDoneBar?: bool,
    hideIcon?: bool,
  }

  declare class Picker extends React$Component<PickerProps> {}

  declare export default typeof Picker;
}

