// flow-typed signature: 80a22815b1bc9c9aa356f5d0ee009c49
// flow-typed version: <<STUB>>/react-infinite-scroller-with-scroll-element_v^1.0.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-infinite-scroller-with-scroll-element'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-infinite-scroller-with-scroll-element' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-infinite-scroller-with-scroll-element/dist/InfiniteScroll' {
  declare module.exports: any;
}

declare module 'react-infinite-scroller-with-scroll-element/docs/gulpfile' {
  declare module.exports: any;
}

declare module 'react-infinite-scroller-with-scroll-element/docs/js/script' {
  declare module.exports: any;
}

declare module 'react-infinite-scroller-with-scroll-element/docs/src/index' {
  declare module.exports: any;
}

declare module 'react-infinite-scroller-with-scroll-element/src/InfiniteScroll' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-infinite-scroller-with-scroll-element/dist/InfiniteScroll.js' {
  declare module.exports: $Exports<'react-infinite-scroller-with-scroll-element/dist/InfiniteScroll'>;
}
declare module 'react-infinite-scroller-with-scroll-element/docs/gulpfile.js' {
  declare module.exports: $Exports<'react-infinite-scroller-with-scroll-element/docs/gulpfile'>;
}
declare module 'react-infinite-scroller-with-scroll-element/docs/js/script.js' {
  declare module.exports: $Exports<'react-infinite-scroller-with-scroll-element/docs/js/script'>;
}
declare module 'react-infinite-scroller-with-scroll-element/docs/src/index.js' {
  declare module.exports: $Exports<'react-infinite-scroller-with-scroll-element/docs/src/index'>;
}
declare module 'react-infinite-scroller-with-scroll-element/src/InfiniteScroll.js' {
  declare module.exports: $Exports<'react-infinite-scroller-with-scroll-element/src/InfiniteScroll'>;
}
