// flow-typed signature: f9d66914c978f2b6c7fd409a7b9b9b42
// flow-typed version: <<STUB>>/react-native-typography_v1.2.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-typography'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-typography' {
  declare module.exports: any;
}
