// flow-typed signature: e67b2128378a7fb62bd52e66a117c624
// flow-typed version: <<STUB>>/react-navigation_v1.0.0-beta.26/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation' {
  declare module.exports: any;
}
