// flow-typed signature: cb305834ab55a493438180fa9c27fad0
// flow-typed version: <<STUB>>/react-textarea-autosize_v^4.0.5/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textarea-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textarea-autosize/dist/react-textarea-autosize' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.min' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/es/calculateNodeHeight' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/es/index' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/lib/calculateNodeHeight' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textarea-autosize/dist/react-textarea-autosize.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.min.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.min'>;
}
declare module 'react-textarea-autosize/es/calculateNodeHeight.js' {
  declare module.exports: $Exports<'react-textarea-autosize/es/calculateNodeHeight'>;
}
declare module 'react-textarea-autosize/es/index.js' {
  declare module.exports: $Exports<'react-textarea-autosize/es/index'>;
}
declare module 'react-textarea-autosize/lib/calculateNodeHeight.js' {
  declare module.exports: $Exports<'react-textarea-autosize/lib/calculateNodeHeight'>;
}
declare module 'react-textarea-autosize/lib/index.js' {
  declare module.exports: $Exports<'react-textarea-autosize/lib/index'>;
}
