// flow-typed signature: 035b7348b5830524b803d87212f30009
// flow-typed version: <<STUB>>/react-async-hook_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-hook/dist/index.es' {
  declare module.exports: any;
}

declare module 'react-async-hook/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-hook/dist/index.es.js' {
  declare module.exports: $Exports<'react-async-hook/dist/index.es'>;
}
declare module 'react-async-hook/dist/index.js' {
  declare module.exports: $Exports<'react-async-hook/dist/index'>;
}
