// flow-typed signature: 87c8c141566d076e2d8ce1e04ecbf5f3
// flow-typed version: <<STUB>>/react-router-dom_v^4.0.0-beta.7/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-dom/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/BrowserRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/HashRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/index' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Link' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/matchPath' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/NavLink' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Prompt' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Redirect' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Route' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Router' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/Switch' {
  declare module.exports: any;
}

declare module 'react-router-dom/es/withRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/HashRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/Link' {
  declare module.exports: any;
}

declare module 'react-router-dom/matchPath' {
  declare module.exports: any;
}

declare module 'react-router-dom/MemoryRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/NavLink' {
  declare module.exports: any;
}

declare module 'react-router-dom/Prompt' {
  declare module.exports: any;
}

declare module 'react-router-dom/Redirect' {
  declare module.exports: any;
}

declare module 'react-router-dom/Route' {
  declare module.exports: any;
}

declare module 'react-router-dom/Router' {
  declare module.exports: any;
}

declare module 'react-router-dom/StaticRouter' {
  declare module.exports: any;
}

declare module 'react-router-dom/Switch' {
  declare module.exports: any;
}

declare module 'react-router-dom/umd/react-router-dom' {
  declare module.exports: any;
}

declare module 'react-router-dom/umd/react-router-dom.min' {
  declare module.exports: any;
}

declare module 'react-router-dom/withRouter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-dom/BrowserRouter.js' {
  declare module.exports: $Exports<'react-router-dom/BrowserRouter'>;
}
declare module 'react-router-dom/es/BrowserRouter.js' {
  declare module.exports: $Exports<'react-router-dom/es/BrowserRouter'>;
}
declare module 'react-router-dom/es/HashRouter.js' {
  declare module.exports: $Exports<'react-router-dom/es/HashRouter'>;
}
declare module 'react-router-dom/es/index.js' {
  declare module.exports: $Exports<'react-router-dom/es/index'>;
}
declare module 'react-router-dom/es/Link.js' {
  declare module.exports: $Exports<'react-router-dom/es/Link'>;
}
declare module 'react-router-dom/es/matchPath.js' {
  declare module.exports: $Exports<'react-router-dom/es/matchPath'>;
}
declare module 'react-router-dom/es/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router-dom/es/MemoryRouter'>;
}
declare module 'react-router-dom/es/NavLink.js' {
  declare module.exports: $Exports<'react-router-dom/es/NavLink'>;
}
declare module 'react-router-dom/es/Prompt.js' {
  declare module.exports: $Exports<'react-router-dom/es/Prompt'>;
}
declare module 'react-router-dom/es/Redirect.js' {
  declare module.exports: $Exports<'react-router-dom/es/Redirect'>;
}
declare module 'react-router-dom/es/Route.js' {
  declare module.exports: $Exports<'react-router-dom/es/Route'>;
}
declare module 'react-router-dom/es/Router.js' {
  declare module.exports: $Exports<'react-router-dom/es/Router'>;
}
declare module 'react-router-dom/es/StaticRouter.js' {
  declare module.exports: $Exports<'react-router-dom/es/StaticRouter'>;
}
declare module 'react-router-dom/es/Switch.js' {
  declare module.exports: $Exports<'react-router-dom/es/Switch'>;
}
declare module 'react-router-dom/es/withRouter.js' {
  declare module.exports: $Exports<'react-router-dom/es/withRouter'>;
}
declare module 'react-router-dom/HashRouter.js' {
  declare module.exports: $Exports<'react-router-dom/HashRouter'>;
}
declare module 'react-router-dom/index' {
  declare module.exports: $Exports<'react-router-dom'>;
}
declare module 'react-router-dom/index.js' {
  declare module.exports: $Exports<'react-router-dom'>;
}
declare module 'react-router-dom/Link.js' {
  declare module.exports: $Exports<'react-router-dom/Link'>;
}
declare module 'react-router-dom/matchPath.js' {
  declare module.exports: $Exports<'react-router-dom/matchPath'>;
}
declare module 'react-router-dom/MemoryRouter.js' {
  declare module.exports: $Exports<'react-router-dom/MemoryRouter'>;
}
declare module 'react-router-dom/NavLink.js' {
  declare module.exports: $Exports<'react-router-dom/NavLink'>;
}
declare module 'react-router-dom/Prompt.js' {
  declare module.exports: $Exports<'react-router-dom/Prompt'>;
}
declare module 'react-router-dom/Redirect.js' {
  declare module.exports: $Exports<'react-router-dom/Redirect'>;
}
declare module 'react-router-dom/Route.js' {
  declare module.exports: $Exports<'react-router-dom/Route'>;
}
declare module 'react-router-dom/Router.js' {
  declare module.exports: $Exports<'react-router-dom/Router'>;
}
declare module 'react-router-dom/StaticRouter.js' {
  declare module.exports: $Exports<'react-router-dom/StaticRouter'>;
}
declare module 'react-router-dom/Switch.js' {
  declare module.exports: $Exports<'react-router-dom/Switch'>;
}
declare module 'react-router-dom/umd/react-router-dom.js' {
  declare module.exports: $Exports<'react-router-dom/umd/react-router-dom'>;
}
declare module 'react-router-dom/umd/react-router-dom.min.js' {
  declare module.exports: $Exports<'react-router-dom/umd/react-router-dom.min'>;
}
declare module 'react-router-dom/withRouter.js' {
  declare module.exports: $Exports<'react-router-dom/withRouter'>;
}
