// flow-typed signature: 945cd904850eeca8414f8e34587bb528
// flow-typed version: <<STUB>>/react-remarkable_v^1.1.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-remarkable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-remarkable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-remarkable/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-remarkable/dist/index.js' {
  declare module.exports: $Exports<'react-remarkable/dist/index'>;
}
