// flow-typed signature: 12ab11615dc44ebfea392e40b67a020e
// flow-typed version: <<STUB>>/react-mentions_v2.4.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-mentions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-mentions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-mentions/es/Highlighter' {
  declare module.exports: any;
}

declare module 'react-mentions/es/index' {
  declare module.exports: any;
}

declare module 'react-mentions/es/LoadingIndicator' {
  declare module.exports: any;
}

declare module 'react-mentions/es/Mention' {
  declare module.exports: any;
}

declare module 'react-mentions/es/MentionsInput' {
  declare module.exports: any;
}

declare module 'react-mentions/es/Suggestion' {
  declare module.exports: any;
}

declare module 'react-mentions/es/SuggestionsOverlay' {
  declare module.exports: any;
}

declare module 'react-mentions/es/utils' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/Highlighter' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/index' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/LoadingIndicator' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/Mention' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/MentionsInput' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/Suggestion' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/SuggestionsOverlay' {
  declare module.exports: any;
}

declare module 'react-mentions/lib/utils' {
  declare module.exports: any;
}

declare module 'react-mentions/umd/react-mentions' {
  declare module.exports: any;
}

declare module 'react-mentions/umd/react-mentions.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-mentions/es/Highlighter.js' {
  declare module.exports: $Exports<'react-mentions/es/Highlighter'>;
}
declare module 'react-mentions/es/index.js' {
  declare module.exports: $Exports<'react-mentions/es/index'>;
}
declare module 'react-mentions/es/LoadingIndicator.js' {
  declare module.exports: $Exports<'react-mentions/es/LoadingIndicator'>;
}
declare module 'react-mentions/es/Mention.js' {
  declare module.exports: $Exports<'react-mentions/es/Mention'>;
}
declare module 'react-mentions/es/MentionsInput.js' {
  declare module.exports: $Exports<'react-mentions/es/MentionsInput'>;
}
declare module 'react-mentions/es/Suggestion.js' {
  declare module.exports: $Exports<'react-mentions/es/Suggestion'>;
}
declare module 'react-mentions/es/SuggestionsOverlay.js' {
  declare module.exports: $Exports<'react-mentions/es/SuggestionsOverlay'>;
}
declare module 'react-mentions/es/utils.js' {
  declare module.exports: $Exports<'react-mentions/es/utils'>;
}
declare module 'react-mentions/lib/Highlighter.js' {
  declare module.exports: $Exports<'react-mentions/lib/Highlighter'>;
}
declare module 'react-mentions/lib/index.js' {
  declare module.exports: $Exports<'react-mentions/lib/index'>;
}
declare module 'react-mentions/lib/LoadingIndicator.js' {
  declare module.exports: $Exports<'react-mentions/lib/LoadingIndicator'>;
}
declare module 'react-mentions/lib/Mention.js' {
  declare module.exports: $Exports<'react-mentions/lib/Mention'>;
}
declare module 'react-mentions/lib/MentionsInput.js' {
  declare module.exports: $Exports<'react-mentions/lib/MentionsInput'>;
}
declare module 'react-mentions/lib/Suggestion.js' {
  declare module.exports: $Exports<'react-mentions/lib/Suggestion'>;
}
declare module 'react-mentions/lib/SuggestionsOverlay.js' {
  declare module.exports: $Exports<'react-mentions/lib/SuggestionsOverlay'>;
}
declare module 'react-mentions/lib/utils.js' {
  declare module.exports: $Exports<'react-mentions/lib/utils'>;
}
declare module 'react-mentions/umd/react-mentions.js' {
  declare module.exports: $Exports<'react-mentions/umd/react-mentions'>;
}
declare module 'react-mentions/umd/react-mentions.min.js' {
  declare module.exports: $Exports<'react-mentions/umd/react-mentions.min'>;
}
