// flow-typed signature: 9ab0e60355c0dbfc2a67ab1bb2229719
// flow-typed version: <<STUB>>/react-navigation-props-mapper_v0.1.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-navigation-props-mapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-navigation-props-mapper' {
  declare module.exports: any;
}
