// flow-typed signature: 80b0017129ba75aa9424b55d6795fdff
// flow-typed version: <<STUB>>/react-native-keyboard-spacer_vx/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-keyboard-spacer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-keyboard-spacer' {
  declare export type KeyboardSpacerProps = {
    topSpacing?: number,
    animationConfig?: Object,
    onToggle?: (keyboardState: bool, keyboardSpace: number) => void,
  };
  declare class KeyboardSpacer extends React$Component<KeyboardSpacerProps> {}
  declare module.exports: typeof KeyboardSpacer;
}
