// flow-typed signature: 1bb7c6e73766f12473441ae11cd13596
// flow-typed version: <<STUB>>/react-helmet_v5.x/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet/es/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/es/HelmetConstants' {
  declare module.exports: any;
}

declare module 'react-helmet/es/HelmetUtils' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/Helmet' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/HelmetConstants' {
  declare module.exports: any;
}

declare module 'react-helmet/lib/HelmetUtils' {
  declare module.exports: any;
}

declare module 'react-helmet/test/HelmetDeclarativeTest' {
  declare module.exports: any;
}

declare module 'react-helmet/test/HelmetTest' {
  declare module.exports: any;
}

declare module 'react-helmet/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-helmet/es/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/es/Helmet'>;
}
declare module 'react-helmet/es/HelmetConstants.js' {
  declare module.exports: $Exports<'react-helmet/es/HelmetConstants'>;
}
declare module 'react-helmet/es/HelmetUtils.js' {
  declare module.exports: $Exports<'react-helmet/es/HelmetUtils'>;
}
declare module 'react-helmet/lib/Helmet.js' {
  declare module.exports: $Exports<'react-helmet/lib/Helmet'>;
}
declare module 'react-helmet/lib/HelmetConstants.js' {
  declare module.exports: $Exports<'react-helmet/lib/HelmetConstants'>;
}
declare module 'react-helmet/lib/HelmetUtils.js' {
  declare module.exports: $Exports<'react-helmet/lib/HelmetUtils'>;
}
declare module 'react-helmet/test/HelmetDeclarativeTest.js' {
  declare module.exports: $Exports<'react-helmet/test/HelmetDeclarativeTest'>;
}
declare module 'react-helmet/test/HelmetTest.js' {
  declare module.exports: $Exports<'react-helmet/test/HelmetTest'>;
}
declare module 'react-helmet/test/test.js' {
  declare module.exports: $Exports<'react-helmet/test/test'>;
}
