// flow-typed signature: 55d74017ecad2954e1eab0931095108e
// flow-typed version: <<STUB>>/react-app-rewire-styled-components_v^3.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-app-rewire-styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-app-rewire-styled-components' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-app-rewire-styled-components/dist/index' {
  declare module.exports: any;
}

declare module 'react-app-rewire-styled-components/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-app-rewire-styled-components/dist/index.js' {
  declare module.exports: $Exports<'react-app-rewire-styled-components/dist/index'>;
}
declare module 'react-app-rewire-styled-components/src/index.js' {
  declare module.exports: $Exports<'react-app-rewire-styled-components/src/index'>;
}
