// flow-typed signature: c7f5b43c5e1b103e542648906166804f
// flow-typed version: <<STUB>>/redis-tag-cache_v1.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redis-tag-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
import type { RedisOptions } from 'ioredis';

declare module 'redis-tag-cache' {
  declare type Options = {
    defaultTimeout?: number,
    redis?: RedisOptions,
  }

  declare type SetOptions = {
     timeout?: number
  }

  declare class TagCache {
    constructor(options?: Options): void;
    get(...keys: Array<string>): Promise<?any>;
    set(key: string, data: any, tags: Array<string>, options?: SetOptions): Promise<void>;
    invalidate(...tags: Array<string>): Promise<void>;
  }

  declare module.exports: typeof TagCache;
}

