// flow-typed signature: d11d41223a90775d23a96362be51c936
// flow-typed version: <<STUB>>/redraft_v^0.8.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redraft'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redraft' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redraft/lib/ContentNode' {
  declare module.exports: any;
}

declare module 'redraft/lib/createStyleRenderer' {
  declare module.exports: any;
}

declare module 'redraft/lib/defaultOptions' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/arrayEqual' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/checkCleanup' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/checkJoin' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/getKeyGenerator' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/pushString' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/stubContentBlock' {
  declare module.exports: any;
}

declare module 'redraft/lib/helpers/warn' {
  declare module.exports: any;
}

declare module 'redraft/lib/index' {
  declare module.exports: any;
}

declare module 'redraft/lib/RawParser' {
  declare module.exports: any;
}

declare module 'redraft/lib/render' {
  declare module.exports: any;
}

declare module 'redraft/lib/withDecorators' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redraft/lib/ContentNode.js' {
  declare module.exports: $Exports<'redraft/lib/ContentNode'>;
}
declare module 'redraft/lib/createStyleRenderer.js' {
  declare module.exports: $Exports<'redraft/lib/createStyleRenderer'>;
}
declare module 'redraft/lib/defaultOptions.js' {
  declare module.exports: $Exports<'redraft/lib/defaultOptions'>;
}
declare module 'redraft/lib/helpers/arrayEqual.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/arrayEqual'>;
}
declare module 'redraft/lib/helpers/checkCleanup.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/checkCleanup'>;
}
declare module 'redraft/lib/helpers/checkJoin.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/checkJoin'>;
}
declare module 'redraft/lib/helpers/getKeyGenerator.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/getKeyGenerator'>;
}
declare module 'redraft/lib/helpers/pushString.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/pushString'>;
}
declare module 'redraft/lib/helpers/stubContentBlock.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/stubContentBlock'>;
}
declare module 'redraft/lib/helpers/warn.js' {
  declare module.exports: $Exports<'redraft/lib/helpers/warn'>;
}
declare module 'redraft/lib/index.js' {
  declare module.exports: $Exports<'redraft/lib/index'>;
}
declare module 'redraft/lib/RawParser.js' {
  declare module.exports: $Exports<'redraft/lib/RawParser'>;
}
declare module 'redraft/lib/render.js' {
  declare module.exports: $Exports<'redraft/lib/render'>;
}
declare module 'redraft/lib/withDecorators.js' {
  declare module.exports: $Exports<'redraft/lib/withDecorators'>;
}
