// flow-typed signature: 78b6b0fc3ee7604a3e67412a6cd6a121
// flow-typed version: <<STUB>>/request-ip_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'request-ip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'request-ip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'request-ip/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'request-ip/dist/index.js' {
  declare module.exports: $Exports<'request-ip/dist/index'>;
}
