// flow-typed signature: 3bbe1f5fd24a38093d3be861a7f3eeb7
// flow-typed version: <<STUB>>/rethinkhaberdashery_v2.3.32/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rethinkhaberdashery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rethinkhaberdashery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rethinkhaberdashery/browserify' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/connection' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/cursor' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/dequeue' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/error' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/helper' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/index' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/metadata' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/pool_master' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/pool' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/protodef' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/term' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/transform_stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/lib/writable_stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/long_test/config' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/long_test/discovery' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/long_test/static' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/long_test/writable_stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/accessing-reql' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/administration' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/aggregation' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/backtrace' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/client-backtrace' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/config' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/control-structures' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/coverage' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/cursor' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/dates-and-times' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/datum' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/dequeue' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/document-manipulation' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/error' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/extra' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/geo' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/joins' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/manipulating-databases' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/manipulating-tables' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/math-and-logic' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/multiple-require' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/nodeify' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/pool_legacy' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/selecting-data' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/stable' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/string-manipulation' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/transform-stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/transformations' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/common' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/database' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/document' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/error' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/group' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/helper' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/index' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/node' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/protodef' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/query' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/selection' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/sequence' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/util/fake_server/table' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/writable-stream' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/test/writing-data' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/tool/generateTest' {
  declare module.exports: any;
}

declare module 'rethinkhaberdashery/tool/ulimit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rethinkhaberdashery/browserify.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/browserify'>;
}
declare module 'rethinkhaberdashery/lib/connection.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/connection'>;
}
declare module 'rethinkhaberdashery/lib/cursor.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/cursor'>;
}
declare module 'rethinkhaberdashery/lib/dequeue.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/dequeue'>;
}
declare module 'rethinkhaberdashery/lib/error.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/error'>;
}
declare module 'rethinkhaberdashery/lib/helper.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/helper'>;
}
declare module 'rethinkhaberdashery/lib/index.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/index'>;
}
declare module 'rethinkhaberdashery/lib/metadata.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/metadata'>;
}
declare module 'rethinkhaberdashery/lib/pool_master.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/pool_master'>;
}
declare module 'rethinkhaberdashery/lib/pool.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/pool'>;
}
declare module 'rethinkhaberdashery/lib/protodef.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/protodef'>;
}
declare module 'rethinkhaberdashery/lib/stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/stream'>;
}
declare module 'rethinkhaberdashery/lib/term.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/term'>;
}
declare module 'rethinkhaberdashery/lib/transform_stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/transform_stream'>;
}
declare module 'rethinkhaberdashery/lib/writable_stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/lib/writable_stream'>;
}
declare module 'rethinkhaberdashery/long_test/config.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/long_test/config'>;
}
declare module 'rethinkhaberdashery/long_test/discovery.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/long_test/discovery'>;
}
declare module 'rethinkhaberdashery/long_test/static.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/long_test/static'>;
}
declare module 'rethinkhaberdashery/long_test/writable_stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/long_test/writable_stream'>;
}
declare module 'rethinkhaberdashery/test/accessing-reql.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/accessing-reql'>;
}
declare module 'rethinkhaberdashery/test/administration.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/administration'>;
}
declare module 'rethinkhaberdashery/test/aggregation.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/aggregation'>;
}
declare module 'rethinkhaberdashery/test/backtrace.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/backtrace'>;
}
declare module 'rethinkhaberdashery/test/client-backtrace.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/client-backtrace'>;
}
declare module 'rethinkhaberdashery/test/config.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/config'>;
}
declare module 'rethinkhaberdashery/test/control-structures.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/control-structures'>;
}
declare module 'rethinkhaberdashery/test/coverage.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/coverage'>;
}
declare module 'rethinkhaberdashery/test/cursor.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/cursor'>;
}
declare module 'rethinkhaberdashery/test/dates-and-times.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/dates-and-times'>;
}
declare module 'rethinkhaberdashery/test/datum.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/datum'>;
}
declare module 'rethinkhaberdashery/test/dequeue.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/dequeue'>;
}
declare module 'rethinkhaberdashery/test/document-manipulation.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/document-manipulation'>;
}
declare module 'rethinkhaberdashery/test/error.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/error'>;
}
declare module 'rethinkhaberdashery/test/extra.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/extra'>;
}
declare module 'rethinkhaberdashery/test/geo.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/geo'>;
}
declare module 'rethinkhaberdashery/test/joins.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/joins'>;
}
declare module 'rethinkhaberdashery/test/manipulating-databases.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/manipulating-databases'>;
}
declare module 'rethinkhaberdashery/test/manipulating-tables.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/manipulating-tables'>;
}
declare module 'rethinkhaberdashery/test/math-and-logic.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/math-and-logic'>;
}
declare module 'rethinkhaberdashery/test/multiple-require.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/multiple-require'>;
}
declare module 'rethinkhaberdashery/test/nodeify.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/nodeify'>;
}
declare module 'rethinkhaberdashery/test/pool_legacy.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/pool_legacy'>;
}
declare module 'rethinkhaberdashery/test/selecting-data.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/selecting-data'>;
}
declare module 'rethinkhaberdashery/test/stable.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/stable'>;
}
declare module 'rethinkhaberdashery/test/stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/stream'>;
}
declare module 'rethinkhaberdashery/test/string-manipulation.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/string-manipulation'>;
}
declare module 'rethinkhaberdashery/test/transform-stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/transform-stream'>;
}
declare module 'rethinkhaberdashery/test/transformations.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/transformations'>;
}
declare module 'rethinkhaberdashery/test/util/common.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/common'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/database.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/database'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/document.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/document'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/error.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/error'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/group.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/group'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/helper.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/helper'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/index.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/index'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/node.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/node'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/protodef.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/protodef'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/query.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/query'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/selection.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/selection'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/sequence.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/sequence'>;
}
declare module 'rethinkhaberdashery/test/util/fake_server/table.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/util/fake_server/table'>;
}
declare module 'rethinkhaberdashery/test/writable-stream.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/writable-stream'>;
}
declare module 'rethinkhaberdashery/test/writing-data.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/test/writing-data'>;
}
declare module 'rethinkhaberdashery/tool/generateTest.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/tool/generateTest'>;
}
declare module 'rethinkhaberdashery/tool/ulimit.js' {
  declare module.exports: $Exports<'rethinkhaberdashery/tool/ulimit'>;
}
