// flow-typed signature: 9d1c99b3d5cd0cb7ce1484adb1ad5554
// flow-typed version: <<STUB>>/rethinkdb-inspector_v^0.3.3/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rethinkdb-inspector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rethinkdb-inspector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rethinkdb-inspector/dist/error' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/dist/get-query-string' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/dist/index' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-polyfill_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-env_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-flow_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-stage-2_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/husky_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/performance-now_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/rethinkdbdash_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/flow-typed/npm/rimraf_vx.x.x' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/src/error' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/src/get-query-string' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/src/index' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/src/test/index.test' {
  declare module.exports: any;
}

declare module 'rethinkdb-inspector/src/test/on-query-complete.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rethinkdb-inspector/dist/error.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/dist/error'>;
}
declare module 'rethinkdb-inspector/dist/get-query-string.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/dist/get-query-string'>;
}
declare module 'rethinkdb-inspector/dist/index.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/dist/index'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-polyfill_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-polyfill_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-env_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-preset-env_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-flow_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-preset-flow_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/babel-preset-stage-2_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/babel-preset-stage-2_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/eslint-plugin-babel_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/husky_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/husky_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/jest_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/jest_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/performance-now_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/performance-now_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/prettier_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/rethinkdbdash_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/rethinkdbdash_vx.x.x'>;
}
declare module 'rethinkdb-inspector/flow-typed/npm/rimraf_vx.x.x.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/flow-typed/npm/rimraf_vx.x.x'>;
}
declare module 'rethinkdb-inspector/src/error.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/src/error'>;
}
declare module 'rethinkdb-inspector/src/get-query-string.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/src/get-query-string'>;
}
declare module 'rethinkdb-inspector/src/index.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/src/index'>;
}
declare module 'rethinkdb-inspector/src/test/index.test.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/src/test/index.test'>;
}
declare module 'rethinkdb-inspector/src/test/on-query-complete.test.js' {
  declare module.exports: $Exports<'rethinkdb-inspector/src/test/on-query-complete.test'>;
}
