// flow-typed signature: baee76376f183ef5fc657dfa65e21c66
// flow-typed version: <<STUB>>/s3-image-uploader_v^1.0.7/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   's3-image-uploader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 's3-image-uploader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 's3-image-uploader/index' {
  declare module.exports: $Exports<'s3-image-uploader'>;
}
declare module 's3-image-uploader/index.js' {
  declare module.exports: $Exports<'s3-image-uploader'>;
}
