// flow-typed signature: b1526dfe80666c5f35a1bbcf301c9ecc
// flow-typed version: <<STUB>>/session-rethinkdb_v^2.0.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'session-rethinkdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'session-rethinkdb' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'session-rethinkdb/index' {
  declare module.exports: $Exports<'session-rethinkdb'>;
}
declare module 'session-rethinkdb/index.js' {
  declare module.exports: $Exports<'session-rethinkdb'>;
}
