// flow-typed signature: 8660b67d17e423e24e0530c755914a76
// flow-typed version: <<STUB>>/slugg_v^1.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slugg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slugg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slugg/slugg' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slugg/slugg.js' {
  declare module.exports: $Exports<'slugg/slugg'>;
}
