// flow-typed signature: 8f063755e65f032485439ac4cefffded
// flow-typed version: <<STUB>>/snarkdown_vx.x.x/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snarkdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snarkdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snarkdown/dist/snarkdown.es' {
  declare module.exports: any;
}

declare module 'snarkdown/dist/snarkdown' {
  declare module.exports: any;
}

declare module 'snarkdown/dist/snarkdown.umd' {
  declare module.exports: any;
}

declare module 'snarkdown/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snarkdown/dist/snarkdown.es.js' {
  declare module.exports: $Exports<'snarkdown/dist/snarkdown.es'>;
}
declare module 'snarkdown/dist/snarkdown.js' {
  declare module.exports: $Exports<'snarkdown/dist/snarkdown'>;
}
declare module 'snarkdown/dist/snarkdown.umd.js' {
  declare module.exports: $Exports<'snarkdown/dist/snarkdown.umd'>;
}
declare module 'snarkdown/src/index.js' {
  declare module.exports: $Exports<'snarkdown/src/index'>;
}
