// flow-typed signature: 1cef27a8caf9ee6e3ccafed1f735bd12
// flow-typed version: <<STUB>>/storybook-addon-actions_v^3.2.13/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook-addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook-addon-actions' {
  declare module.exports: any;
}
