// flow-typed signature: 68358bc2bb6add3943d67e0592a63d74
// flow-typed version: <<STUB>>/string-similarity_v1.2.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'string-similarity'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'string-similarity' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'string-similarity/compare-strings' {
  declare module.exports: any;
}

declare module 'string-similarity/compare-strings.spec' {
  declare module.exports: any;
}

declare module 'string-similarity/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'string-similarity/compare-strings.js' {
  declare module.exports: $Exports<'string-similarity/compare-strings'>;
}
declare module 'string-similarity/compare-strings.spec.js' {
  declare module.exports: $Exports<'string-similarity/compare-strings.spec'>;
}
declare module 'string-similarity/gulpfile.js' {
  declare module.exports: $Exports<'string-similarity/gulpfile'>;
}
