// flow-typed signature: 1af86b7488831c23890ae26878a08080
// flow-typed version: <<STUB>>/stripe_v^4.15.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stripe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stripe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stripe/examples/webhook-signing/express' {
  declare module.exports: any;
}

declare module 'stripe/lib/Error' {
  declare module.exports: any;
}

declare module 'stripe/lib/MultipartDataGenerator' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Accounts' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplePayDomains' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplicationFeeRefunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplicationFees' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Balance' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/BitcoinReceivers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ChargeRefunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Charges' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CountrySpecs' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Coupons' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CustomerCards' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Customers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CustomerSubscriptions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Disputes' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/EphemeralKeys' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Events' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/FileUploads' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/InvoiceItems' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Invoices' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/LoginLinks' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/OrderReturns' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Orders' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Payouts' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Plans' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Products' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/RecipientCards' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Recipients' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Refunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SKUs' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Sources' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SubscriptionItems' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Subscriptions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ThreeDSecure' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Tokens' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/TransferReversals' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Transfers' {
  declare module.exports: any;
}

declare module 'stripe/lib/stripe' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeMethod.basic' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeMethod' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeResource' {
  declare module.exports: any;
}

declare module 'stripe/lib/utils' {
  declare module.exports: any;
}

declare module 'stripe/lib/Webhooks' {
  declare module.exports: any;
}

declare module 'stripe/test' {
  declare module.exports: any;
}

declare module 'stripe/test/Error.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/flows.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Account.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/ApplePayDomains.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/ApplicationFeeRefunds.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/ApplicationFees.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Balance.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/BitcoinReceivers.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/ChargeRefunds.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Charges.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/CountrySpecs.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Coupons.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/CustomerCards.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Customers.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/CustomerSubscriptions.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Disputes.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/EphemeralKeys.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Events.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/FileUploads.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/InvoiceItems.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Invoices.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/LoginLinks.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/OrderReturns.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Orders.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Payouts.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Plans.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Products.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/RecipientCards.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Recipients.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Refunds.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/SKUs.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Sources.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/SubscriptionItems.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Subscriptions.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/ThreeDSecure.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Tokens.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/TransferReversals.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/resources/Transfers.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/stripe.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/StripeResource.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/testUtils' {
  declare module.exports: any;
}

declare module 'stripe/test/utils.spec' {
  declare module.exports: any;
}

declare module 'stripe/test/Webhook.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stripe/examples/webhook-signing/express.js' {
  declare module.exports: $Exports<'stripe/examples/webhook-signing/express'>;
}
declare module 'stripe/lib/Error.js' {
  declare module.exports: $Exports<'stripe/lib/Error'>;
}
declare module 'stripe/lib/MultipartDataGenerator.js' {
  declare module.exports: $Exports<'stripe/lib/MultipartDataGenerator'>;
}
declare module 'stripe/lib/resources/Accounts.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Accounts'>;
}
declare module 'stripe/lib/resources/ApplePayDomains.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplePayDomains'>;
}
declare module 'stripe/lib/resources/ApplicationFeeRefunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplicationFeeRefunds'>;
}
declare module 'stripe/lib/resources/ApplicationFees.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplicationFees'>;
}
declare module 'stripe/lib/resources/Balance.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Balance'>;
}
declare module 'stripe/lib/resources/BitcoinReceivers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/BitcoinReceivers'>;
}
declare module 'stripe/lib/resources/ChargeRefunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ChargeRefunds'>;
}
declare module 'stripe/lib/resources/Charges.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Charges'>;
}
declare module 'stripe/lib/resources/CountrySpecs.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CountrySpecs'>;
}
declare module 'stripe/lib/resources/Coupons.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Coupons'>;
}
declare module 'stripe/lib/resources/CustomerCards.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CustomerCards'>;
}
declare module 'stripe/lib/resources/Customers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Customers'>;
}
declare module 'stripe/lib/resources/CustomerSubscriptions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CustomerSubscriptions'>;
}
declare module 'stripe/lib/resources/Disputes.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Disputes'>;
}
declare module 'stripe/lib/resources/EphemeralKeys.js' {
  declare module.exports: $Exports<'stripe/lib/resources/EphemeralKeys'>;
}
declare module 'stripe/lib/resources/Events.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Events'>;
}
declare module 'stripe/lib/resources/FileUploads.js' {
  declare module.exports: $Exports<'stripe/lib/resources/FileUploads'>;
}
declare module 'stripe/lib/resources/InvoiceItems.js' {
  declare module.exports: $Exports<'stripe/lib/resources/InvoiceItems'>;
}
declare module 'stripe/lib/resources/Invoices.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Invoices'>;
}
declare module 'stripe/lib/resources/LoginLinks.js' {
  declare module.exports: $Exports<'stripe/lib/resources/LoginLinks'>;
}
declare module 'stripe/lib/resources/OrderReturns.js' {
  declare module.exports: $Exports<'stripe/lib/resources/OrderReturns'>;
}
declare module 'stripe/lib/resources/Orders.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Orders'>;
}
declare module 'stripe/lib/resources/Payouts.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Payouts'>;
}
declare module 'stripe/lib/resources/Plans.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Plans'>;
}
declare module 'stripe/lib/resources/Products.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Products'>;
}
declare module 'stripe/lib/resources/RecipientCards.js' {
  declare module.exports: $Exports<'stripe/lib/resources/RecipientCards'>;
}
declare module 'stripe/lib/resources/Recipients.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Recipients'>;
}
declare module 'stripe/lib/resources/Refunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Refunds'>;
}
declare module 'stripe/lib/resources/SKUs.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SKUs'>;
}
declare module 'stripe/lib/resources/Sources.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Sources'>;
}
declare module 'stripe/lib/resources/SubscriptionItems.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SubscriptionItems'>;
}
declare module 'stripe/lib/resources/Subscriptions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Subscriptions'>;
}
declare module 'stripe/lib/resources/ThreeDSecure.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ThreeDSecure'>;
}
declare module 'stripe/lib/resources/Tokens.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Tokens'>;
}
declare module 'stripe/lib/resources/TransferReversals.js' {
  declare module.exports: $Exports<'stripe/lib/resources/TransferReversals'>;
}
declare module 'stripe/lib/resources/Transfers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Transfers'>;
}
declare module 'stripe/lib/stripe.js' {
  declare module.exports: $Exports<'stripe/lib/stripe'>;
}
declare module 'stripe/lib/StripeMethod.basic.js' {
  declare module.exports: $Exports<'stripe/lib/StripeMethod.basic'>;
}
declare module 'stripe/lib/StripeMethod.js' {
  declare module.exports: $Exports<'stripe/lib/StripeMethod'>;
}
declare module 'stripe/lib/StripeResource.js' {
  declare module.exports: $Exports<'stripe/lib/StripeResource'>;
}
declare module 'stripe/lib/utils.js' {
  declare module.exports: $Exports<'stripe/lib/utils'>;
}
declare module 'stripe/lib/Webhooks.js' {
  declare module.exports: $Exports<'stripe/lib/Webhooks'>;
}
declare module 'stripe/test.js' {
  declare module.exports: $Exports<'stripe/test'>;
}
declare module 'stripe/test/Error.spec.js' {
  declare module.exports: $Exports<'stripe/test/Error.spec'>;
}
declare module 'stripe/test/flows.spec.js' {
  declare module.exports: $Exports<'stripe/test/flows.spec'>;
}
declare module 'stripe/test/resources/Account.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Account.spec'>;
}
declare module 'stripe/test/resources/ApplePayDomains.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/ApplePayDomains.spec'>;
}
declare module 'stripe/test/resources/ApplicationFeeRefunds.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/ApplicationFeeRefunds.spec'>;
}
declare module 'stripe/test/resources/ApplicationFees.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/ApplicationFees.spec'>;
}
declare module 'stripe/test/resources/Balance.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Balance.spec'>;
}
declare module 'stripe/test/resources/BitcoinReceivers.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/BitcoinReceivers.spec'>;
}
declare module 'stripe/test/resources/ChargeRefunds.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/ChargeRefunds.spec'>;
}
declare module 'stripe/test/resources/Charges.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Charges.spec'>;
}
declare module 'stripe/test/resources/CountrySpecs.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/CountrySpecs.spec'>;
}
declare module 'stripe/test/resources/Coupons.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Coupons.spec'>;
}
declare module 'stripe/test/resources/CustomerCards.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/CustomerCards.spec'>;
}
declare module 'stripe/test/resources/Customers.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Customers.spec'>;
}
declare module 'stripe/test/resources/CustomerSubscriptions.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/CustomerSubscriptions.spec'>;
}
declare module 'stripe/test/resources/Disputes.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Disputes.spec'>;
}
declare module 'stripe/test/resources/EphemeralKeys.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/EphemeralKeys.spec'>;
}
declare module 'stripe/test/resources/Events.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Events.spec'>;
}
declare module 'stripe/test/resources/FileUploads.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/FileUploads.spec'>;
}
declare module 'stripe/test/resources/InvoiceItems.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/InvoiceItems.spec'>;
}
declare module 'stripe/test/resources/Invoices.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Invoices.spec'>;
}
declare module 'stripe/test/resources/LoginLinks.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/LoginLinks.spec'>;
}
declare module 'stripe/test/resources/OrderReturns.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/OrderReturns.spec'>;
}
declare module 'stripe/test/resources/Orders.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Orders.spec'>;
}
declare module 'stripe/test/resources/Payouts.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Payouts.spec'>;
}
declare module 'stripe/test/resources/Plans.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Plans.spec'>;
}
declare module 'stripe/test/resources/Products.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Products.spec'>;
}
declare module 'stripe/test/resources/RecipientCards.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/RecipientCards.spec'>;
}
declare module 'stripe/test/resources/Recipients.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Recipients.spec'>;
}
declare module 'stripe/test/resources/Refunds.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Refunds.spec'>;
}
declare module 'stripe/test/resources/SKUs.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/SKUs.spec'>;
}
declare module 'stripe/test/resources/Sources.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Sources.spec'>;
}
declare module 'stripe/test/resources/SubscriptionItems.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/SubscriptionItems.spec'>;
}
declare module 'stripe/test/resources/Subscriptions.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Subscriptions.spec'>;
}
declare module 'stripe/test/resources/ThreeDSecure.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/ThreeDSecure.spec'>;
}
declare module 'stripe/test/resources/Tokens.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Tokens.spec'>;
}
declare module 'stripe/test/resources/TransferReversals.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/TransferReversals.spec'>;
}
declare module 'stripe/test/resources/Transfers.spec.js' {
  declare module.exports: $Exports<'stripe/test/resources/Transfers.spec'>;
}
declare module 'stripe/test/stripe.spec.js' {
  declare module.exports: $Exports<'stripe/test/stripe.spec'>;
}
declare module 'stripe/test/StripeResource.spec.js' {
  declare module.exports: $Exports<'stripe/test/StripeResource.spec'>;
}
declare module 'stripe/test/testUtils.js' {
  declare module.exports: $Exports<'stripe/test/testUtils'>;
}
declare module 'stripe/test/utils.spec.js' {
  declare module.exports: $Exports<'stripe/test/utils.spec'>;
}
declare module 'stripe/test/Webhook.spec.js' {
  declare module.exports: $Exports<'stripe/test/Webhook.spec'>;
}
