// flow-typed signature: a7d313191ab4bdafa615176a5802a8a2
// flow-typed version: <<STUB>>/then-queue_v1.3.0/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'then-queue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'then-queue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'then-queue/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'then-queue/index' {
  declare module.exports: $Exports<'then-queue'>;
}
declare module 'then-queue/index.js' {
  declare module.exports: $Exports<'then-queue'>;
}
declare module 'then-queue/test/index.js' {
  declare module.exports: $Exports<'then-queue/test/index'>;
}
