// flow-typed signature: 005da1297e0ad6a94b3d535bb51f87a7
// flow-typed version: <<STUB>>/web-push_v^3.2.2/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'web-push'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'web-push' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'web-push/src/cli' {
  declare module.exports: any;
}

declare module 'web-push/src/encryption-helper' {
  declare module.exports: any;
}

declare module 'web-push/src/index' {
  declare module.exports: any;
}

declare module 'web-push/src/vapid-helper' {
  declare module.exports: any;
}

declare module 'web-push/src/web-push-error' {
  declare module.exports: any;
}

declare module 'web-push/src/web-push-lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'web-push/src/cli.js' {
  declare module.exports: $Exports<'web-push/src/cli'>;
}
declare module 'web-push/src/encryption-helper.js' {
  declare module.exports: $Exports<'web-push/src/encryption-helper'>;
}
declare module 'web-push/src/index.js' {
  declare module.exports: $Exports<'web-push/src/index'>;
}
declare module 'web-push/src/vapid-helper.js' {
  declare module.exports: $Exports<'web-push/src/vapid-helper'>;
}
declare module 'web-push/src/web-push-error.js' {
  declare module.exports: $Exports<'web-push/src/web-push-error'>;
}
declare module 'web-push/src/web-push-lib.js' {
  declare module.exports: $Exports<'web-push/src/web-push-lib'>;
}
