// flow-typed signature: 75ad28471a8b109519e597cfe8a7e0c9
// flow-typed version: <<STUB>>/webpack-module-manifest-plugin_v^0.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-module-manifest-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-module-manifest-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-module-manifest-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'webpack-module-manifest-plugin/src/index' {
  declare module.exports: any;
}

declare module 'webpack-module-manifest-plugin/src/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-module-manifest-plugin/lib/index.js' {
  declare module.exports: $Exports<'webpack-module-manifest-plugin/lib/index'>;
}
declare module 'webpack-module-manifest-plugin/src/index.js' {
  declare module.exports: $Exports<'webpack-module-manifest-plugin/src/index'>;
}
declare module 'webpack-module-manifest-plugin/src/index.test.js' {
  declare module.exports: $Exports<'webpack-module-manifest-plugin/src/index.test'>;
}
