// flow-typed signature: 923c90a052a1b40ad9eadb023c489b00
// flow-typed version: <<STUB>>/@vx/event_v^0.0.127/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/event/build/index' {
  declare module.exports: any;
}

declare module '@vx/event/build/localPoint' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/event/build/index.js' {
  declare module.exports: $Exports<'@vx/event/build/index'>;
}
declare module '@vx/event/build/localPoint.js' {
  declare module.exports: $Exports<'@vx/event/build/localPoint'>;
}
