// flow-typed signature: 8c5c7e282e820b67637f4ac2d760dec0
// flow-typed version: <<STUB>>/@vx/gradient_v^0.0.129/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/gradient'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/gradient' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/gradient/build/gradients/DarkgreenGreen' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/LightgreenGreen' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/LinearGradient' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/OrangeRed' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/PinkBlue' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/PinkRed' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/PurpleOrange' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/PurpleRed' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/PurpleTeal' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/RadialGradient' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/SteelPurple' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/gradients/TealBlue' {
  declare module.exports: any;
}

declare module '@vx/gradient/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/gradient/build/gradients/DarkgreenGreen.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/DarkgreenGreen'>;
}
declare module '@vx/gradient/build/gradients/LightgreenGreen.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/LightgreenGreen'>;
}
declare module '@vx/gradient/build/gradients/LinearGradient.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/LinearGradient'>;
}
declare module '@vx/gradient/build/gradients/OrangeRed.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/OrangeRed'>;
}
declare module '@vx/gradient/build/gradients/PinkBlue.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/PinkBlue'>;
}
declare module '@vx/gradient/build/gradients/PinkRed.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/PinkRed'>;
}
declare module '@vx/gradient/build/gradients/PurpleOrange.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/PurpleOrange'>;
}
declare module '@vx/gradient/build/gradients/PurpleRed.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/PurpleRed'>;
}
declare module '@vx/gradient/build/gradients/PurpleTeal.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/PurpleTeal'>;
}
declare module '@vx/gradient/build/gradients/RadialGradient.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/RadialGradient'>;
}
declare module '@vx/gradient/build/gradients/SteelPurple.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/SteelPurple'>;
}
declare module '@vx/gradient/build/gradients/TealBlue.js' {
  declare module.exports: $Exports<'@vx/gradient/build/gradients/TealBlue'>;
}
declare module '@vx/gradient/build/index.js' {
  declare module.exports: $Exports<'@vx/gradient/build/index'>;
}
