// flow-typed signature: d5ba0ce5dc460f15e091aafd082ea665
// flow-typed version: <<STUB>>/@vx/grid_v^0.0.131/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@vx/grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@vx/grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@vx/grid/build/grids/Columns' {
  declare module.exports: any;
}

declare module '@vx/grid/build/grids/Grid' {
  declare module.exports: any;
}

declare module '@vx/grid/build/grids/Rows' {
  declare module.exports: any;
}

declare module '@vx/grid/build/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@vx/grid/build/grids/Columns.js' {
  declare module.exports: $Exports<'@vx/grid/build/grids/Columns'>;
}
declare module '@vx/grid/build/grids/Grid.js' {
  declare module.exports: $Exports<'@vx/grid/build/grids/Grid'>;
}
declare module '@vx/grid/build/grids/Rows.js' {
  declare module.exports: $Exports<'@vx/grid/build/grids/Rows'>;
}
declare module '@vx/grid/build/index.js' {
  declare module.exports: $Exports<'@vx/grid/build/index'>;
}
