// @flow
const constants = require('./constants');
const {
  DATE,
  BRIAN_ID,
  MAX_ID,
  BRYN_ID,
  BLOCKED_USER_ID,
  PENDING_USER_ID,
  PREVIOUS_MEMBER_USER_ID,
  SPECTRUM_GENERAL_CHANNEL_ID,
  SPECTRUM_PRIVATE_CHANNEL_ID,
  PAYMENTS_GENERAL_CHANNEL_ID,
  PAYMENTS_PRIVATE_CHANNEL_ID,
} = constants;

module.exports = [
  {
    id: '1',
    createdAt: new Date(DATE),
    userId: MAX_ID,
    channelId: SPECTRUM_GENERAL_CHANNEL_ID,
    isOwner: true,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '2',
    createdAt: new Date(DATE),
    userId: BRIAN_ID,
    channelId: SPECTRUM_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '3',
    createdAt: new Date(DATE),
    userId: BRYN_ID,
    channelId: SPECTRUM_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '4',
    createdAt: new Date(DATE),
    userId: BLOCKED_USER_ID,
    channelId: SPECTRUM_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: false,
    isBlocked: true,
    isPending: false,
    receiveNotifications: true,
  },

  {
    id: '5',
    createdAt: new Date(DATE),
    userId: MAX_ID,
    channelId: SPECTRUM_PRIVATE_CHANNEL_ID,
    isOwner: true,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '6',
    createdAt: new Date(DATE),
    userId: BRIAN_ID,
    channelId: SPECTRUM_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '7',
    createdAt: new Date(DATE),
    userId: BRYN_ID,
    channelId: SPECTRUM_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '8',
    createdAt: new Date(DATE),
    userId: BLOCKED_USER_ID,
    channelId: SPECTRUM_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: false,
    isBlocked: true,
    isPending: false,
    receiveNotifications: true,
  },

  {
    id: '9',
    createdAt: new Date(DATE),
    userId: MAX_ID,
    channelId: PAYMENTS_GENERAL_CHANNEL_ID,
    isOwner: true,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '10',
    createdAt: new Date(DATE),
    userId: BRIAN_ID,
    channelId: PAYMENTS_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '11',
    createdAt: new Date(DATE),
    userId: BRYN_ID,
    channelId: PAYMENTS_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '12',
    createdAt: new Date(DATE),
    userId: BLOCKED_USER_ID,
    channelId: PAYMENTS_GENERAL_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: false,
    isBlocked: true,
    isPending: false,
    receiveNotifications: true,
  },

  {
    id: '13',
    createdAt: new Date(DATE),
    userId: MAX_ID,
    channelId: PAYMENTS_PRIVATE_CHANNEL_ID,
    isOwner: true,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '14',
    createdAt: new Date(DATE),
    userId: BRIAN_ID,
    channelId: PAYMENTS_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '15',
    createdAt: new Date(DATE),
    userId: BRYN_ID,
    channelId: PAYMENTS_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: true,
    isBlocked: false,
    isPending: false,
    receiveNotifications: true,
  },
  {
    id: '16',
    createdAt: new Date(DATE),
    userId: BLOCKED_USER_ID,
    channelId: PAYMENTS_PRIVATE_CHANNEL_ID,
    isOwner: false,
    isModerator: false,
    isMember: false,
    isBlocked: true,
    isPending: false,
    receiveNotifications: true,
  },
];
