FROM withspectrum/installer:latest AS installer

# -----------------------------------------------------------------------------
# development
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine as development
WORKDIR /app

COPY --from=installer /app/node_modules /app/node_modules
COPY --from=installer /app/athena/node_modules /app/athena/node_modules

CMD ["yarn", "dev:athena"]

# -----------------------------------------------------------------------------
# build
# -----------------------------------------------------------------------------
FROM development as builder

COPY . /app
RUN yarn build:athena

# -----------------------------------------------------------------------------
# production
# -----------------------------------------------------------------------------
FROM node:9.7.0-alpine
WORKDIR /app

COPY --from=builder /app/build-athena /app

ENV NODE_ENV=production
CMD ["node", "main.js"]
